-- CITYMO — Injection des lignes du devis Villa Mamouri dans PR-2026-10-0002
-- Source : Devis_Mamouri_Tableaux_Complets.xlsx (176 articles, prix à 0)
-- Ne touche QUE les lignes de PR-2026-10-0002 (INSERT uniquement, aucun UPDATE / DELETE).
-- S'arrête sans rien faire si le devis contient déjà des lignes.
-- IMPORTANT : fermer le devis PR-2026-10-0002 dans l'ERP avant d'exécuter, puis le rouvrir.

DO $$
DECLARE
  did UUID;
BEGIN
  SELECT id INTO did FROM public.crm_devis WHERE reference = 'PR-2026-10-0002' LIMIT 1;
  IF did IS NULL THEN
    RAISE EXCEPTION 'Devis PR-2026-10-0002 introuvable';
  END IF;

  IF EXISTS (SELECT 1 FROM public.crm_devis_lignes WHERE devis_id = did) THEN
    RAISE NOTICE 'Le devis PR-2026-10-0002 contient déjà des lignes — aucune modification.';
    RETURN;
  END IF;

  INSERT INTO public.crm_devis_lignes (
    devis_id, ordre, type, designation, description,
    article_id, categorie_id, quantite, unite, prix_ht, remise, tva, total_ht
  ) VALUES
  (did, 0, 'titre', 'PORTES', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 1, 'article', 'Porte d’entrée principale 1', '- Fourniture et pose d’une porte d’entrée toute hauteur, design moderne et minimaliste, finition noire/anthracite mate, avec panneaux verticaux et lignes discrètes selon l’image. 277cm/207cm/p:30cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 2, 'article', 'Grande poignée verticale 1', '- Fourniture et pose d’une longue poignée verticale en finition bronze, laiton brossé ou inox brossé, placée sur la porte principale selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 3, 'article', 'Habillage autour de la porte', '- Habillage de l’encadrement de porte en finition noire/anthracite mate, avec panneaux verticaux et lignes discrètes selon l’image.600cm/277cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 4, 'article', 'Éclairage LED périphérique', '- Ruban LED blanc chaud dissimulé sur le contour du plafond d’entrée, pour souligner l’encadrement de la porte et créer une ambiance premium.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 5, 'article', 'Porte d’entrée principale 2', '- Fourniture et pose d’une porte d’entrée toute hauteur, design moderne et minimaliste, finition noire/anthracite mate, avec panneaux verticaux et lignes discrètes selon l’image. Dimensions estimées : 240 cm / 103 cm / P : 30 cm.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 6, 'article', 'Grande poignée verticale 2', '- Fourniture et pose d’une longue poignée verticale en finition bronze, laiton brossé ou inox brossé, placée sur la porte principale selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 7, 'article', 'Porte d’entrée principale 3', '- Fourniture et pose d’une porte d’entrée toute hauteur, design moderne et minimaliste, finition noire/anthracite mate, avec panneaux verticaux et lignes discrètes selon l’image. Dimensions estimées : 240 cm / 103 cm / P : 30 cm.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 8, 'article', 'Grande poignée verticale 3', '- Fourniture et pose d’une longue poignée verticale en finition bronze, laiton brossé ou inox brossé, placée sur la porte principale selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 9, 'titre', 'HALL D’ENTRÉE', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 10, 'article', 'Console table', '- Fourniture et pose console avec tiroirs en bois chêne dimension: 90cm/35cm/20cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 11, 'article', 'Miroir', '- Fourniture et pose d’un Miroir arrondi rectangle au-dessus console, dimension : 1m/50cm cadre gold bronze', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 12, 'article', 'Placard', '- Fourniture et pose placard avec toute hauteur Porte avec cintre rail et Étagères, poignées gold bronze, dimension 3m/45cm/40, Caisson importation européenne hydrofuge et anti bactérien 1er choix, Porte en bois CLEAF ou EGGER (Made in Italy), haute finition, hydrofuge et antibactérien. Éclairage LED Intégré avec Détecteur - Fonctionnement automatique. Peinture laquée', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 13, 'article', 'Ouvert manteaux niche', '- Fourniture et pose vertical ouvert Armoire niche avec supérieur étagère, cintres, et inférieur tiroir, dimension 3m/45cm/40, matière: contreplaqué bardage, eclairage LED Intégré', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 14, 'article', 'Mur Panneau à gauche', '- Fourniture et pose Mur derriere Miroir et console matière: bardage HDF laquée 1m/3m', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 15, 'article', 'Mur a droite', '- Fourniture et pose Mur bardage HDF laquée 1m/3m', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 16, 'article', 'Porte de débarras RDC couloir', E'- Fourniture et pose Porte Invisible en bois contreplaqué chênes isoplane 1er choix,\n• Latte 8 mm pour deux faces\n• Face A et\n• Face B.\n• Dimension: 211cm/85cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 17, 'titre', 'PALIER / COULOIR', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 18, 'article', 'Habillage Mural', '- Fourniture et pose HABILLAGE MURAL et BARDAGE avec Structure en bois HDF Finition peinture haute finition écologique.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 19, 'article', 'Porte', E'PORTES INTERIEURS INVISIBLE EPAISSEUR 5.50 CM :\n• Fourniture et pose Portes intérieures INVISIBLES (Épaisseur 5.5cm), toute hauteur, haute finition en bois contreplaqué avec structure en bois rouge (isoplane).\n• Face A :\n• Latte 8 mm\n• Vernis Polistuc 1er choix Fabriqué en Italie chene.\n• Face B : laquée HDF 8 mm,\n• Vernis Polistuc 1er choix Fabriqué en Italie.\n• Accessoires inclus: Charnières, canaux.\n• Joint de porte isolant contre les infiltrations du vent, anti-bruit et anti-choc.\n• Dimension: 214cm/102cm/30cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 20, 'titre', 'CUISINE', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 21, 'article', 'Cuisine moderne', '- Fourniture et pose d’une cuisine moderne et ilot central sur mesure selon le plan et l’image 3D.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 22, 'article', 'Caissons', '- Caissons d’importation européenne, hydrofuges et antibactériens, 1er choix.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 23, 'article', 'Portes meubles', '- Portes de meubles en MDF stratifié / HPL laminate avec poignées intégrées, haute finition.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 24, 'article', 'Rangements et étagères', '- Rangements pratiques et étagères intégrées selon la conception de la cuisine.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 25, 'article', 'Charnières', '- Accessoires de marque BLUM ou similaire : charnières premier choix avec système soft-close.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 26, 'article', 'Tiroirs / bloc-tiroir', '- Tiroirs et bloc-tiroir intégrés pour rangement fonctionnel.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 27, 'article', 'Casseroliers', '- Casseroliers hydrauliques intégrés.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 28, 'article', 'Range-couverts', '- Range-couverts intégré dans les tiroirs.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 29, 'article', 'Épicier', '- Épicier intégré pour rangement alimentaire.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 30, 'article', 'Protection sous évier', '- Protection sous évier en aluminium.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 31, 'article', 'Plan de travail', '- Plan de travail compris dans la prestation, matériel : céramique / porcelaine ou Dekton selon l’image 3D. (a la sélection d’échantillon)', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 32, 'article', 'Table à manger', '- Fourniture et pose d’une table à manger en finition bois clair chêne, design moderne, intégrée à l’espace cuisine selon l’image et le plan. Mesure table 140cm/90cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 33, 'article', 'Chaises', '- Fourniture de 4 chaises de salle à manger avec assise et dossier rembourrés en tissu beige/crème, structure métallique noire, style moderne selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 34, 'article', 'Hotte intégrée', '- Fourniture et pose d’une hotte de cuisine intégrée de marque BOSH DUL93MA50M de 90 cm finition noire moderne, installée au-dessus de la plaque de cuisson, avec système d’aspiration adapté à la cuisine et intégration esthétique selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 35, 'article', 'Filtre a eau integrer sur le plan de travail', '- Fourniture et pose d’une hotte de cuisine intégrée de marque Ecosoft avec 6 filtres de minereaux', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 36, 'titre', 'SALON', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 37, 'article', 'Mur TV principal', '- Fourniture et pose d’un meuble mural TV avec Structure en bois HDF Finition peinture haute finition écologique sur mesure avec panneau encastré, cadre crème autour de la TV et accents en chêne selon l’image et le plan.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 38, 'article', 'Console basse TV', '- Console basse longue suspendue ou posée sous la TV, en bois chêne avec façade rainurée/cannelée et éclairage LED discret en partie basse.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 39, 'article', 'Étagères de présentation gauche', '- Étagères avec verticales à gauche du mur TV, avec niches décoratives et éclairage LED intégré blanc chaud. Porte vitrée aluminium CARRÉ style italien haute finition, charnières encastrées, Verre clair.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 40, 'article', 'Niche étagères droite', '- Petite niche verticale intégrée près de la TV, avec étagères décoratives en finition bois/chêne et éclairage intégré.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 41, 'article', 'Panneau mural rainuré vertical', '- Grand panneau mural cannelé/rainuré sur le côté droit du mur TV, en finition crème ou ton chêne selon le design. (En prenant en considération les éléments du chauffage)', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 42, 'article', 'Éclairage LED autour du cadre TV', '- Ruban LED dissimulé autour du panneau TV et de la console basse, créant un effet rétroéclairé blanc chaud.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 43, 'article', 'Éclairage LED des étagères', '- Éclairage LED intégré dans les étagères de présentation pour mise en valeur des objets décoratifs.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 44, 'article', 'Suspension noire et blanche', '- Grande suspension décorative en forme de dôme au-dessus de l’espace salon, finition noire avec diffuseur blanc.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 45, 'article', 'Canapé L', '- Canapé L, assise tapissée en tissu beige/crème chaud, style moderne et confortable selon l’image et le plan. 285cm/220cm/p:75cm/h:35cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 46, 'article', 'Table basse', '- Table basse rectangulaire en bois finition chêne clair, avec plateau inférieur de rangement intégré. 100cm/55cm/45cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 47, 'titre', 'CHAMBRE PARENTALE', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 48, 'sous_titre', 'Mur tête de lit', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 49, 'article', 'Lit tapissé', '- Fourniture et pose d’un lit bas tapissé en tissu beige/crème, avec tête de lit rembourrée et pied de lit intégré, style moderne et chaleureux selon l’image.180cm/200cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 50, 'article', 'Matelas', '- Matelas', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 51, 'article', 'Tables de chevet', '- Tables de chevet en bois clair ou chêne, avec tiroir de rangement, placées de chaque côté du lit selon l’aménagement. 50cm/P:40cm, L’hauteur selon hauteur du lit', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 52, 'article', 'Appliques murales circulaires', '- Ensemble vertical de trois appliques murales décoratives rondes, finition laiton/doré avec éclairage LED intégré, placées sur le mur côté lit.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 53, 'article', 'Panneaux muraux cannelés tête de lit', '- Habillage mural toute hauteur derrière le lit, composé de panneaux verticaux rainurés/cannelés en finition crème ou chêne clair en bois chêne.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 54, 'article', 'Panneau central effet pierre / marbre', '- Panneau vertical décoratif centré au-dessus du lit, en finition pierre naturelle ou marbre clair, encadré par un éclairage LED discret.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 55, 'article', 'LED verticales autour du panneau central', '- Éclairage LED dissimulé sur les côtés du panneau central en pierre/marbre, lumière blanc chaud pour effet décoratif.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 56, 'article', 'Porte WC', E'PORTES INTERIEURS INVISIBLE EPAISSEUR 5.50 CM :\n• Fourniture et pose Portes intérieures INVISIBLES (Épaisseur 5.5cm), toute hauteur, haute finition en bois contreplaqué avec\n• structure en bois rouge (isoplane).\n• Face A :\n• Latte 8 mm\n• Vernis Polistuc 1er choix Fabriqué en Italie chene.\n• Face B : 8 mm Noyer (Américain La Cema) isoplane 1er choix,\n• Vernis Polistuc 1er choix Fabriqué en Italie.\n• Accessoires inclus: Charnières, canaux.\n• Joint de porte isolant contre les infiltrations du vent, anti-bruit et anti-choc.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 57, 'sous_titre', 'Mur TV, bureau et porte chambre', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 58, 'article', 'Mur TV principal', '- Fourniture et pose d’un meuble mural TV avec Structure en bois HDF Finition peinture haute finition écologique sur mesure avec panneau encastré, cadre crème autour de la TV selon l’image et le plan.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 59, 'article', 'Console basse TV', '- Meuble bas long sous TV avec tiroirs, suspendu, avec façade rainurée/cannelée finition chêne clair.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 60, 'article', 'LED sous console TV', '- Éclairage LED blanc chaud placé sous la console pour effet flottant.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 61, 'article', 'LED autour de la TV', '- Éclairage LED dissimulé autour du panneau TV, effet rétroéclairé.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 62, 'article', 'Étagères décoratives côté gauche', '- Habillage mural toute hauteur derrière le lit, composé de panneaux verticaux rainurés/cannelés en finition crème ou chêne clair en bois chêne. Étagères ouvertes avec niches décoratives et LED intégrées, finition bois clair chêne.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 63, 'article', 'Bureau en L / coiffeuse', '- Petit espace bureau en L (voir plan) ou coiffeuse intégrée à gauche, avec plateau bois et rangement. Fourniture et pose d’un Miroir arrondi rectangle au-dessus console, dimension : 1m/50cm cadre gold bronze', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 64, 'article', 'Chaise bureau / coiffeuse', '- Chaise tapissée beige/crème avec structure assortie, placée devant le bureau/coiffeuse.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 65, 'article', 'Tableau décoratif noir et blanc', '- Tableau mural abstrait noir et blanc encadré, placé près de la porte.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 66, 'article', 'Porte chambre', E'PORTES INTERIEURS INVISIBLE EPAISSEUR 5.50 CM :\n• Fourniture et pose Portes intérieures INVISIBLES (Épaisseur 5.5 cm), toute hauteur, haute finition\n• en bois contreplaqué Noyer (Américain La Cema) isoplane 1er choix, ou Peinture Laquée avec structure en bois rouge.\n• Latte 8 mm pour deux faces\n• Face A et\n• Face B et laine de roche isolant acoustique. (isoplane)\n• Vernis Polistuc 1er choix Fabriqué en Italie.\n• Accessoires inclus : Charnières, canaux.\n• Joint de porte isolant contre les infiltrations du vent, anti-bruit et anti-choc.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 67, 'sous_titre', 'Meuble étagères et tableau mural', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 68, 'article', 'Meuble étagères intégré', '- Meuble vertical intégré avec étagères ouvertes, niches décoratives, tiroirs et rangement bas en bois chêne.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 69, 'article', 'Étagères ouvertes éclairées', '- Étagères en bois clair avec éclairage LED blanc chaud intégré pour objets décoratifs.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 70, 'article', 'Tiroirs intégrés', '- Bloc de tiroirs intégré dans le meuble, finition chêne clair avec poignées discrètes.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 71, 'article', 'Habillage de mur de tableau', '- Fourniture et pose HABILLAGE MURAL avec Structure en bois HDF Finition peinture haute finition écologique.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 72, 'article', 'Tableau mural rétroéclairé', '- Tableau mural rectangulaire avec lignes lumineuses abstraites et rétroéclairage LED blanc chaud.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 73, 'article', 'Porte dressing', E'PORTES INTERIEURS INVISIBLE EPAISSEUR 5.50 CM :\n• Fourniture et pose Portes intérieures INVISIBLES (Épaisseur 5.5cm), toute hauteur, haute finition en bois contreplaqué avec\n• structure en bois rouge.\n• Face A :\n• Latte 8 mm\n• Vernis Polistuc 1er choix Fabriqué en Italie chene.\n• Face B : 8 mm Noyer (Américain La Cema) isoplane 1er choix,\n• Vernis Polistuc 1er choix Fabriqué en Italie.\n• Accessoires inclus: Charnières, canaux.\n• Joint de porte isolant contre les infiltrations du vent, anti-bruit et anti-choc.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 74, 'sous_titre', 'Coin assise', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 75, 'article', 'Canapé', '- Fourniture et pose d’un canapé 3 places, forme arrondie, tapissé en tissu beige/crème, avec assise généreuse et dossier bas, style moderne et chaleureux selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 76, 'article', 'Tables basses rondes', '- Fourniture et pose de deux tables basses rondes gigognes, finition claire type pierre/marbre ou laque mate, avec piètements cylindriques assortis.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 77, 'article', 'Lampadaire', '- Fourniture et pose d’un lampadaire design avec grand diffuseur sphérique blanc et pied fin, finition claire/gris doux, style contemporain.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 78, 'titre', 'SALLE DE BAIN PARENTALE', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 79, 'article', 'Meuble vasque suspendu', '- Meuble vasque sur mesure suspendu avec façade rainurée/cannelée, tiroirs intégrés en bois contreplaqué Noyer (Américain La Cema) isoplane 1er choix', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 80, 'article', 'Éclairage LED sous vasque', '- Ruban LED blanc chaud intégré sous le meuble vasque.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 81, 'article', 'Plan / tablette du meuble vasque', '- Support horizontal sur mesure pour la vasque, adapté aux dimensions de la salle de bain. Hors marbre/pierre.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 82, 'article', 'Miroir mural', '- Grand miroir mural au-dessus de la vasque, forme arrondie/ovale selon l’image avec LED, cadre noir', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 83, 'article', 'Etagères de niches de salle de bain', '- Etagères de Niches de rangement intégrées en bois contreplaqué Noyer (Américain La Cema) isoplane 1ers choix réalisés selon les dimensions disponibles.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 84, 'titre', 'DRESSING', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 85, 'article', 'Dressing haut de gamme avec accessoires', '- Fourniture, pose et personnalisation d’un dressing haut de gamme sur mesure avec accessoires intégrés.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 86, 'article', 'Caissons dressing', '- Caissons en bois CLEAF ou EGGER, fabrication italienne, haute finition, hydrofuges et antibactériens.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 87, 'article', 'Portes dressing bois', '- Portes de dressing en bois CLEAF ou EGGER, Made in Italy, finition haut de gamme, résistantes à l’humidité et antibactériennes (pour poignées voire l’image)', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 88, 'article', 'Éclairage LED intégré', '- Éclairage LED intégré dans le dressing avec détecteur, fonctionnement automatique à l’ouverture ou au passage.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 89, 'article', 'Tiroirs hydrauliques', '- Tiroirs hydrauliques intégrés avec système de fermeture douce pour un usage pratique et silencieux.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 90, 'article', 'Rangements et étagères', '- Rangements intérieurs et étagères sur mesure pour optimiser l’organisation du dressing.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 91, 'article', 'Penderie fixe', '- Penderie fixe intégrée pour vêtements suspendus, adaptée à la configuration du dressing.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 92, 'article', 'Portes vitrées dressing profil', '- Portes vitrées pour dressing avec profil aluminium carré, style italien, haute finition, cadre gold bronze', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 93, 'article', 'Profil aluminium carré', '- Structure des portes vitrées en profil aluminium carré, finition moderne et élégante, cadre gold bronz', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 94, 'article', 'Charnières encastrées', '- Charnières encastrées pour portes vitrées, permettant une finition discrète et haut de gamme.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 95, 'article', 'Verre bronze', '- Verre bronze pour portes vitrées de dressing, apportant un rendu élégant, moderne et raffiné.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 96, 'article', 'Miroir', '- Fourniture et pose d’un Miroir arrondi rectangle au-dessus console, dimension : 200m/120cm cadre gold bronze', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 97, 'titre', 'CHAMBRE SECONDAIRE', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 98, 'sous_titre', 'Lit et salle de bain', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 99, 'article', 'Lit tapissé', '- Fourniture et pose d’un lit bas tapissé en tissu beige/crème, avec tête de lit rembourrée et pied de lit intégré, style moderne et chaleureux selon l’image. Dimensions : 180 cm × 200 cm.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 100, 'article', 'Matelas', '- Fourniture d’un matelas adapté au lit, dimensions 180 cm × 200 cm', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 101, 'article', 'Tables de chevet', '- Fourniture et pose de tables de chevet en bois clair ou chêne, avec tiroir de rangement, placées de chaque côté du lit selon l’aménagement. Dimensions estimées : L 50 cm × P 40 cm, hauteur selon hauteur du lit.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 102, 'article', 'Tête de lit rembourrée', '- Tête de lit tapissée en tissu beige/crème, composée de deux panneaux rembourrés, intégrée au lit pour un rendu moderne et confortable.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 103, 'article', 'Habillage mural tête de lit', '- Habillage mural horizontal derrière le lit en bois chêne clair, avec finition haute qualité et intégration d’un éclairage LED indirect.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 104, 'article', 'Mur décoratif effet enduit', '- Réalisation d’un mur décoratif effet enduit/texturé beige clair derrière la tête de lit, style minimaliste et haut de gamme.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 105, 'article', 'Éclairage LED derrière tête de lit', '- Éclairage LED dissimulé blanc chaud derrière l’habillage mural en bois, créant un effet lumineux doux et décoratif.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 106, 'article', 'Suspension de chevet', '- Fourniture et pose d’une suspension décorative fine côté chevet, finition noire/bronze avec diffuseur blanc, style moderne.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 107, 'article', 'Porte intérieure invisible', E'- Fourniture et pose d’une porte intérieure invisible, épaisseur 5,50 cm, toute hauteur, haute finition en bois contreplaqué avec structure en bois rouge (isoplane).\n• Face A et B: latte 8 mm, vernis Polistuc 1er choix fabriqué en Italie, finition chêne.\n• Accessoires inclus : charnières et canaux.\n• Joint de porte isolant contre les infiltrations du vent, anti-bruit et anti-choc.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 108, 'article', 'Rideaux doubles', '- Fourniture et pose de rideaux toute hauteur composés d’un voilage blanc transparent et d’un rideau occultant gris/taupe, selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 109, 'article', 'Voilage blanc', '- Voilage léger blanc toute hauteur pour laisser passer la lumière naturelle tout en assurant l’intimité.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 110, 'article', 'Rideau occultant gris', '- Rideau épais gris/taupe toute hauteur, finition élégante, pour occultation et habillage décoratif de la fenêtre.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 111, 'article', 'Miroir mural', '- Grand miroir mural au-dessus de la vasque, forme arrondie/ovale selon l’image avec LED, cadre noir', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 112, 'article', 'Meuble vasque suspendu', '- Meuble vasque sur mesure suspendu avec façade rainurée/cannelée, tiroirs intégrés en bois contreplaqué chêne isoplane 1er choix', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 113, 'article', 'Éclairage LED sous vasque', '- Ruban LED blanc chaud intégré sous le meuble vasque.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 114, 'article', 'Plan / tablette du meuble vasque', '- Support horizontal sur mesure pour la vasque, adapté aux dimensions de la salle de bain. Hors marbre/pierre.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 115, 'sous_titre', 'Meuble TV', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 116, 'article', 'Meuble TV bas', '- Meuble bas sous TV avec tiroirs intégrés, finition claire, design minimaliste et lignes droites selon l’image en laquée', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 117, 'article', 'Panneau arrière TV', '- Panneau décoratif derrière la télévision, finition bois chêne, intégré dans la structure du meuble TV.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 118, 'article', 'Placards hauts', '- Rangements hauts toute largeur au-dessus de la TV, avec portes pleines finition gris clair ou blanc cassé, ouverture discrète sans poignée apparente en laquée.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 119, 'article', 'Niches latérales ouvertes', '- Niches verticales ouvertes de chaque côté de la TV, finition chêne.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 120, 'article', 'Étagères latérales', '- Étagères fines intégrées dans les niches latérales finition chêne.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 121, 'article', 'Éclairage LED intégré', '- Éclairage LED blanc chaud intégré dans les niches et autour du meuble TV et Placards pour créer une ambiance douce et haut de gamme.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 122, 'article', 'Porte intérieure invisible', E'- Fourniture et pose d’une porte intérieure invisible, épaisseur 5,50 cm, toute hauteur, haute finition en bois contreplaqué avec structure en bois rouge (isoplane).\n• Face A et B: latte 8 mm, vernis Polistuc 1er choix fabriqué en Italie, finition chêne.\n• Accessoires inclus : charnières et canaux.\n• Joint de porte isolant contre les infiltrations du vent, anti-bruit et anti-choc.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 123, 'sous_titre', 'Coin bureau', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 124, 'article', 'Plateau bureau', '- Plateau de bureau finition chêne clair, fixé au mur, avec design minimaliste et profondeur adaptée à l’usage.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 125, 'article', 'Chaise bureau', '- Chaise de bureau tapissée en tissu vert sauge, avec pieds fins noirs, style moderne selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 126, 'article', 'Étagères murales bureau', '- Étagères ouvertes au-dessus du bureau, finition claire.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 127, 'article', 'Meuble haut bureau', '- Rangement haut intégré au-dessus du coin bureau, avec portes pleines finition blanc cassé ou gris clair, ouverture discrète.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 128, 'article', 'Panneau mural bureau', '- Habillage mural derrière le bureau en bois clair, assorti au meuble et à la porte, pour un rendu propre et intégré.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 129, 'sous_titre', 'Mur tête de lit', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 130, 'article', 'Lit tapissé', '- Fourniture et pose d’un lit bas tapissé en tissu beige/crème, avec tête de lit rembourrée à panneaux verticaux, pied de lit intégré selon l’image. Dimensions : 160 cm × 200 cm.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 131, 'article', 'Matelas', '- Fourniture d’un matelas adapté au lit, dimensions 160 cm × 200 cm.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 132, 'article', 'Tables de chevet', '- Fourniture et pose de tables de chevet en bois clair ou chêne, avec tiroir de rangement, placées de chaque côté du lit selon l’aménagement. Dimensions estimées : L 50 cm × P 40 cm, hauteur selon hauteur du lit.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 133, 'article', 'Habillage mural tête de lit', '- Habillage mural derrière le lit composé d’un panneau décoratif vertical en bois chêne clair, avec finition haute qualité et intégration d’un éclairage LED indirect.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 134, 'article', 'Mur décoratif Habillage laquee', '- Réalisation d’un mur décoratif effet enduit/texturé beige clair derrière la tête de lit, style minimaliste et haut de gamme.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 135, 'article', 'Panneau mural bois vertical', '- Panneau vertical en bois chêne sur le côté droit de la tête de lit, intégré au mur avec lignes sobres et finition élégante.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 136, 'article', 'LED verticale murale', '- Ruban LED blanc chaud intégré verticalement entre le mur effet enduit et l’habillage bois, pour créer une séparation lumineuse décorative.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 137, 'article', 'Suspension de chevet', '- Fourniture et pose d’une suspension décorative fine côté chevet, finition noire/bronze avec diffuseur blanc', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 138, 'article', 'Applique murale / liseuse', '- Fourniture et pose d’une applique murale ou liseuse fine côté gauche du lit, finition noire/bronze, adaptée à l’éclairage de chevet.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 139, 'article', 'Meuble bas latéral', '- Meuble bas sur mesure à droite du lit, avec tiroirs intégrés, finition bois chêne, associé à une niche noire décorative.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 140, 'article', 'Niche décorative noire', '- Niche horizontale décorative intégrée au meuble latéral droit, finition noire mate, pour objets décoratifs ou rangement léger.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 141, 'article', 'Porte intérieure invisible', E'- Fourniture et pose d’une porte intérieure invisible, épaisseur 5,50 cm, toute hauteur, haute finition en bois contreplaqué avec structure en bois rouge (isoplane).\n• Face A et B : latte 8 mm, vernis Polistuc 1er choix fabriqué en Italie, finition chêne.\n• Accessoires inclus : charnières et canaux.\n• Joint de porte isolant contre les infiltrations du vent, anti-bruit et anti-choc.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 142, 'sous_titre', 'Meuble TV', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 143, 'article', 'Meuble TV bas', '- Meuble bas sous TV avec tiroirs intégrés, finition claire, design minimaliste et lignes droites selon l’image en laquée', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 144, 'article', 'Panneau arrière TV', '- Panneau décoratif derrière la télévision, finition bois chêne, intégré dans la structure du meuble TV.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 145, 'titre', 'CHAMBRE AMINA', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 146, 'sous_titre', 'Lit et coiffeuse', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 147, 'article', 'Lit tapissé', '- Fourniture et pose d’un lit bas tapissé en tissu beige/crème, avec tête de lit rembourrée intégrée, style moderne et chaleureux selon l’image. Dimensions à prévoir selon plan, type 180cm × 200 cm.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 148, 'article', 'Matelas', '- Fourniture d’un matelas adapté au lit, dimensions selon lit choisi.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 149, 'article', 'Bout de lit capitonné', '- Banc / bout de lit capitonné en tissu beige, composé de modules rembourrés, placé devant le lit selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 150, 'article', 'Habillage mural tête de lit', '- Habillage mural derrière le lit avec panneaux décoratifs verticaux en finition beige/taupe, bois clair et éléments rainurés/cannelés.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 151, 'article', 'Panneaux muraux cannelés', '- Panneaux muraux verticaux rainurés/cannelés sur les côtés du mur tête de lit, finition beige clair ou bois clair.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 152, 'article', 'Panneau central mural', '- Grand panneau mural central derrière le lit, finition beige/taupe mate, style minimaliste et haut de gamme.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 153, 'article', 'Éclairage LED horizontal tête de lit', '- Ruban LED blanc chaud intégré horizontalement derrière la tête de lit pour créer un éclairage indirect doux.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 154, 'article', 'LED verticale décorative', '- Éclairage LED vertical intégré entre les panneaux muraux, créant une séparation lumineuse décorative côté coiffeuse.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 155, 'article', 'Tables de chevet', '- Fourniture et pose de tables de chevet intégrées ou suspendues en bois clair/chêne, placées de chaque côté du lit.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 156, 'article', 'Suspensions décoratives de chevet', '- Fourniture et pose de suspensions décoratives fines côté lit, avec globes ou diffuseurs arrondis, finition laiton/bronze selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 157, 'article', 'Tableau décoratif mural', '- Tableau mural décoratif simple avec cadre fin, placé au-dessus du lit, style minimaliste.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 158, 'article', 'Coin coiffeuse / bureau', '- Fourniture et pose d’un coin coiffeuse ou bureau intégré à droite, avec plateau, rangement bas et finition bois foncé/noyer.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 159, 'article', 'Miroir coiffeuse', '- Miroir mural arrondi/rectangulaire avec angles arrondis, cadre fin, placé au-dessus de la coiffeuse.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 160, 'article', 'Chaise coiffeuse', '- Chaise tapissée en tissu brun/terracotta, avec dossier et assise rembourrés, placée devant la coiffeuse.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 161, 'article', 'Étagères latérales', '- Étagères ouvertes intégrées sur le côté droit, finition claire, pour objets décoratifs et range ment léger.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 162, 'article', 'Banquette / bout de lit capitonné', '- Banquette ou bout de l it capitonné en tissu beige/crème, placé face au mur TV selon l’image. (2 places)', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 163, 'sous_titre', 'Mur TV et dressing ouvert', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 164, 'article', 'Panneau mural TV rainuré', '- Habillage mural vertical derrière la TV avec panneaux rainurés/cannelés, finition crème/beige clair, style minimaliste.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 165, 'article', 'Meuble TV bas suspendu', '- Meuble bas long sous la TV, finition bois clair ou chêne, avec tiroirs intégrés et lignes horizontales modernes.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 166, 'article', 'Tablette basse TV', '- Tablette décorative en bois sous la TV, intégrée au meuble bas pour support d’objets décoratifs ou accessoires.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 167, 'article', 'LED derrière meuble TV', '- Éclairage LED blanc chaud dissimulé derrière ou sous le meuble TV pour créer un effet flottant et chaleureux.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 168, 'article', 'Penderie intégrée', '- Zone penderie avec tringle fixe pour vêtements suspendus, intégrée dans le dressing ouvert selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 169, 'article', 'Tiroirs bas Penderie', '- Tiroirs bas intégrés sous la penderie, finition bois clair/chêne, avec ouverture discrète.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 170, 'article', 'Éclairage LED Penderie', '- Rubans LED blanc chaud intégrés dans la zone dressing pour éclairer les vêtements et créer une ambiance haut de gamme.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 171, 'article', 'Placards à portes cannées', '- Placards latéraux avec portes décoratives à effet cannage ou tressage, finition bois clair, style chaleureux et naturel.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 172, 'article', 'Rangement bas avec portes cannées', '- Meuble de rangement bas à gauche avec portes en finition cannage, adapté au rangement textile ou accessoires.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 173, 'article', 'Lampadaire décoratif', '- Lampadaire décoratif avec diffuseur blanc, placé côté mur TV, style moderne et doux selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 174, 'sous_titre', 'Portes dressing', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 175, 'article', 'Portes dressing', '- Fourniture et pose de portes de dressing toute hauteur design moderne, minimaliste et chic selon l’image.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 176, 'article', 'Joints creux verticaux', '- Fines séparations verticales entre les portes, créant un rythme sobre et architectural sur toute la longueur du dressing.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 177, 'article', 'Poignées intégrées verticales', '- Poignées longues et discrètes intégrées dans les portes, finition noire ou bronze foncé, style minimaliste.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 178, 'article', 'Alignement des portes', '- Mise à niveau et alignement parfait des portes pour obtenir une façade continue, propre et harmonieuse.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 179, 'titre', 'REVÊTEMENTS CHAMBRE AMINA', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 180, 'article', 'Dressing haut de gamme avec accessoires', '- Fourniture, pose et personnalisation d’un dressing haut de gamme sur mesure avec accessoires intégrés.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 181, 'article', 'Caissons dressing', '- Caissons en bois CLEAF ou EGGER, fabrication italienne, haute finition, hydrofuges et antibactériens.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 182, 'article', 'Portes dressing bois', '- Portes de dressing en bois CLEAF ou EGGER, Made in Italy, finition haut de gamme, résistantes à l’humidité et antibactériennes (pour poignées voire l’image)', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 183, 'article', 'Éclairage LED intégré', '- Éclairage LED intégré dans le dressing avec détecteur, fonctionnement automatique à l’ouverture ou au passage.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 184, 'article', 'Tiroirs hydrauliques', '- Tiroirs hydrauliques intégrés avec système de fermeture douce pour un usage pratique et silencieux.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 185, 'article', 'Rangements et étagères', '- Rangements intérieurs et étagères sur mesure pour optimiser l’organisation du dressing.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 186, 'article', 'Penderie fixe', '- Penderie fixe intégrée pour vêtements suspendus, adaptée à la configuration du dressing.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 187, 'article', 'Portes vitrées dressing profil', '- Portes vitrées pour dressing avec profil aluminium carré, style italien, haute finition, cadre gold bronze', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 188, 'article', 'Profil aluminium carré', '- Structure des portes vitrées en profil aluminium carré, finition moderne et élégante, cadre gold bronz', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 189, 'article', 'Charnières encastrées', '- Charnières encastrées pour portes vitrées, permettant une finition discrète et haut de gamme.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 190, 'article', 'Verre bronze', '- Verre bronze pour portes vitrées de dressing, apportant un rendu élégant, moderne et raffiné.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 191, 'article', 'Miroir', '- Fourniture et pose d’un Miroir arrondi rectangle au-dessus console, dimension : 200m/120cm cadre gold bronze', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 192, 'titre', 'SALLE DE BAIN AMINA', NULL, NULL, NULL, 0, 'unite', 0, 0, 20, 0),
  (did, 193, 'article', 'Meuble vasque suspendu', '- Fourniture et pose d’un meuble vasque suspendue sur mesure, finition moderne en bois clair/chêne et façade lisse selon l’image. Tiroirs intégrés au meuble vasque, ouverture discrète, finition claire assortie au mobilier.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 194, 'article', 'Plan vasque / tablette', '- Plan horizontal sur mesure pour recevoir la vasque, finition claire, adapté aux dimensions de la salle de bain.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 195, 'article', 'Miroir mural arrondi avec LED', '- Grand miroir mural forme arrondie/ovale avec éclairage LED intégré en périphérie, lumière blanc chaud, placé au-dessus de la vasque.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 196, 'article', 'Éclairage LED sous meuble vasque', '- Ruban LED blanc chaud intégré sous le meuble vasque pour créer un effet flottant et une ambiance douce.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 197, 'article', 'Panneau mural derrière vasque', '- Habillage mural toute hauteur derrière la vasque, finition pierre/marbre clair ou carrelage grand format beige/gris clair.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 198, 'article', 'Sèche-serviettes mural', '- Sèche-serviettes mural design avec barres horizontales, finition noire ou inox brossé, placé près de la vasque.', NULL, NULL, 1, 'unite', 0, 0, 20, 0),
  (did, 199, 'article', 'Porte salle de bain', E'PORTES INTERIEURS INVISIBLE EPAISSEUR 5.50 CM :\n• Fourniture et pose Portes intérieures INVISIBLES (Épaisseur 5.5cm), toute hauteur, haute finition en bois contreplaqué avec\n• Structure en bois rouge (isoplane).\n• Face A :\n• Latte 8 mm\n• Vernis Polistuc 1er choix Fabriqué en Italie chêne.\n• Face B : Miroir toute hauteur\n• Accessoires inclus : Charnières, canaux.\n• Joint de porte isolant contre les infiltrations du vent, anti-bruit et anti-choc.', NULL, NULL, 1, 'unite', 0, 0, 20, 0);

  RAISE NOTICE 'PR-2026-10-0002 : % lignes ajoutées (176 articles).', 200;
END $$;

-- Vérification
SELECT l.ordre, l.type, l.designation
FROM public.crm_devis_lignes l
JOIN public.crm_devis d ON d.id = l.devis_id
WHERE d.reference = 'PR-2026-10-0002'
ORDER BY l.ordre;
