/**
 * FeuilleCaisse.jsx — Feuille de caisse (vue mensuelle + vue globale)
 */
import { useState, useEffect, useMemo } from 'react';
import { Loader2, Plus, Download, FileSpreadsheet, Wallet, Edit2, Trash2, TrendingDown, RefreshCw } from 'lucide-react';
import { useFinanceTransactions } from '../../hooks/useFinanceTransactions';
import { useAuth } from '../../hooks/useAuth';
import {
  isAutoGeneratedTransaction, getSourceBadgeLabel, getSourceModuleMessage,
  runRhPaymentsCashBackfill,
  listAllFinanceTransactions,
  listFinanceTransactionsPaged,
} from '../../services/finance/financeTransactions';
import {
  CASH_RESTART_DATE,
  findCashRestartTransaction,
  splitCashAfterRestart,
  computeRestartMonthTotals,
  computeRestartGlobalTotals,
  isMonthEntirelyBeforeRestart,
  inYearMonth,
} from '../../services/finance/cashRestartLedger';
import { formatSupabaseError } from '../../services/supabase/formatError';
import { listProjectsForSelect } from '../../services/projects/projects';
import { canManageCash, isDGUser } from '../../services/finance/cashAccess';
import { isSuperAdmin } from '../../services/rh/isSuperAdmin';
import {
  validateCashDay, getCashDailyValidation, unlockCashDay,
  getPendingCashValidation, todayIso, yesterdayIso, formatDateFr,
} from '../../services/finance/cashDailyValidation';
import { computeDailyCashTotals, formatDateShortFr } from '../../services/finance/cashDayTotals';
import { consolidateCashSheetTransactions } from '../../services/finance/cashSheetDisplay';
import { dedupeAccidentalChargeCashDuplicates } from '../../services/finance/chargeCashDedupe';
import { auditRhFinanceSync } from '../../services/finance/financeDiagnostics';
import { notifyCashReviewCompleted } from '../../services/notifications/notificationEvents';
import { exportCashSheetPdf, CASH_SHEET_PDF_VERSION } from '../../services/finance/cashSheetPdf';
import { exportCashSheetExcel } from '../../services/finance/cashSheetExport';
import {
  INPUT_STYLE, SELECT_STYLE,
  KpiCard, EmptyState, Modal, FField, FRow,
  formatMAD, genRef,
} from './shared.jsx';

const MOIS_OPTS = [
  { v: 1, l: 'Janvier' }, { v: 2, l: 'Février' }, { v: 3, l: 'Mars' }, { v: 4, l: 'Avril' },
  { v: 5, l: 'Mai' }, { v: 6, l: 'Juin' }, { v: 7, l: 'Juillet' }, { v: 8, l: 'Août' },
  { v: 9, l: 'Septembre' }, { v: 10, l: 'Octobre' }, { v: 11, l: 'Novembre' }, { v: 12, l: 'Décembre' },
];

const MOIS_LABELS = ['', 'Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'];

const TABLE_FILTERS = [
  { id: 'month', label: 'Vue mois' },
  { id: 'all', label: 'Vue globale' },
];

const EMPTY_TX = {
  date: '', sens: 'entree', type_operation: 'alimentation_caisse',
  project_id: '', description: '', montant: '', mode_paiement: 'Espèces',
};

function TxForm({ initial, onSave, onCancel, locked }) {
  const [form, setForm] = useState(initial || EMPTY_TX);
  const [projects, setProjects] = useState([]);
  const set = (k, v) => setForm((p) => ({ ...p, [k]: v }));

  useEffect(() => {
    let cancelled = false;
    listProjectsForSelect()
      .then((rows) => { if (!cancelled) setProjects(rows || []); })
      .catch(() => { if (!cancelled) setProjects([]); });
    return () => { cancelled = true; };
  }, []);

  return (
    <form onSubmit={(e) => {
      e.preventDefault();
      if (locked) return;
      onSave({
        ...form,
        sens: form.sens || 'entree',
        type_operation: form.type_operation || 'alimentation_caisse',
        mode_paiement: form.mode_paiement || 'Espèces',
        montant: parseFloat(form.montant) || 0,
        project_id: form.project_id || null,
      });
    }}
    >
      <FRow>
        <FField label="Date" required>
          <input type="date" value={form.date} onChange={(e) => set('date', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
        </FField>
        <FField label="Type">
          <input value="Alimentation caisse" style={{ ...INPUT_STYLE, background: 'var(--surface-2)' }} readOnly disabled />
        </FField>
        <FField label="Montant (MAD)" required>
          <input type="number" min="0" step="0.01" value={form.montant} onChange={(e) => set('montant', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
        </FField>
        <FField label="Projet lié">
          <select value={form.project_id || ''} onChange={(e) => set('project_id', e.target.value)} style={SELECT_STYLE} disabled={locked}>
            <option value="">— Aucun —</option>
            {projects.map((p) => (
              <option key={p.id} value={p.id}>{p.nom || p.ref || p.id}</option>
            ))}
          </select>
        </FField>
      </FRow>
      <FField label="Description" required>
        <input value={form.description} onChange={(e) => set('description', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
      </FField>
      <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
        <button type="button" className="btn btn-secondary" onClick={onCancel}>Annuler</button>
        {!locked && <button type="submit" className="btn btn-primary">Enregistrer</button>}
      </div>
    </form>
  );
}

function CashSheetTxRow({
  t, history, todayStr, canManage, tryEditTx, tryRemoveTx, notify,
}) {
  const isAuto = isAutoGeneratedTransaction(t) || t.isRecap;
  const badge = getSourceBadgeLabel(t);
  return (
    <tr key={t.id} className={history ? 'feuille-caisse-history-row' : undefined}>
      <td data-label="Date">
        {t.date}
        {t.date === todayStr && (
          <span className="badge badge-green" style={{ marginLeft: 6, fontSize: '0.65rem' }}>J</span>
        )}
      </td>
      <td data-label="Source">
        <span className={`badge ${isAuto ? 'badge-blue' : 'badge-grey'}`} style={{ fontSize: '0.72rem', whiteSpace: 'nowrap' }}>
          {badge}
        </span>
        {history && (
          <span className="badge badge-grey" style={{ marginLeft: 6, fontSize: '0.65rem' }}>Hors calcul</span>
        )}
      </td>
      <td data-label="Contrepartie">{t.contrepartie || '—'}</td>
      <td data-label="Description">{t.description}</td>
      <td data-label="Sortie" style={{ color: history ? 'var(--text-3)' : 'var(--red)', fontWeight: 600 }}>
        {t.sens === 'sortie' ? formatMAD(t.montant) : '—'}
      </td>
      <td data-label="Entrée" style={{ color: history ? 'var(--text-3)' : '#2E7D32', fontWeight: 600 }}>
        {t.sens === 'entree' ? formatMAD(t.montant) : '—'}
      </td>
      <td data-label="Paiement">{t.mode_paiement}</td>
      <td data-label="Actions">
        {!isAuto && canManage && (
          <div style={{ display: 'flex', gap: 6 }}>
            <button type="button" className="btn btn-ghost btn-sm" onClick={() => tryEditTx(t)}><Edit2 size={13} /></button>
            <button type="button" className="btn btn-ghost btn-sm" style={{ color: 'var(--red)' }} onClick={() => tryRemoveTx(t)}><Trash2 size={13} /></button>
          </div>
        )}
        {isAuto && (
          <button type="button" className="btn btn-ghost btn-sm" title="Lecture seule" onClick={() => notify(getSourceModuleMessage(t))}>
            <Edit2 size={13} style={{ opacity: 0.35 }} />
          </button>
        )}
      </td>
    </tr>
  );
}

export default function FeuilleCaisse() {
  const now = new Date();
  const { user } = useAuth();
  const canManage = canManageCash(user);
  const isDG = isDGUser(user);
  const superAdmin = isSuperAdmin(user);

  const [tableFilter, setTableFilter] = useState('month');
  const [year, setYear] = useState(now.getFullYear());
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [allRecords, setAllRecords] = useState([]);
  const [allLoading, setAllLoading] = useState(false);
  const [allError, setAllError] = useState('');
  const [ledgerFromRestart, setLedgerFromRestart] = useState([]);
  const [ledgerLoading, setLedgerLoading] = useState(false);
  const [allReloadToken, setAllReloadToken] = useState(0);
  const [showModal, setShowModal] = useState(false);
  const [editTx, setEditTx] = useState(null);
  const [showBalance, setShowBalance] = useState(false);
  const [balForm, setBalForm] = useState({
    solde_initial: '',
    alimentation: '',
    notes: '',
    force_ouverture: false,
  });
  const [validating, setValidating] = useState(false);
  const [unlocking, setUnlocking] = useState(false);
  const [backfilling, setBackfilling] = useState(false);
  const [toast, setToast] = useState('');
  const [dayValidation, setDayValidation] = useState(null);
  const [pendingJ1Validation, setPendingJ1Validation] = useState(null);
  const [rhAudit, setRhAudit] = useState(null);

  const {
    records, balance, loading, saving, error, configured, reload,
    saveTransaction, removeTransaction, saveBalance,
  } = useFinanceTransactions(year, month);

  const todayStr = todayIso(now);
  const yesterdayStr = yesterdayIso(now);
  const isCurrentMonth = year === now.getFullYear() && month === now.getMonth() + 1;
  const isGlobalView = tableFilter === 'all';
  const periodLabel = `${MOIS_LABELS[month] || month} ${year}`;
  const viewMode = isGlobalView ? 'all' : 'month';
  const selectedDate = todayStr;
  const monthBeforeRestart = isMonthEntirelyBeforeRestart(year, month);

  function bumpAllReload() {
    setAllReloadToken((n) => n + 1);
  }

  const cashSheetRecords = useMemo(
    () => consolidateCashSheetTransactions(records),
    [records],
  );

  const restartLedgerCash = useMemo(
    () => consolidateCashSheetTransactions(ledgerFromRestart),
    [ledgerFromRestart],
  );

  const allCashSheetRecords = useMemo(
    () => consolidateCashSheetTransactions(allRecords),
    [allRecords],
  );

  const restartInfo = useMemo(
    () => findCashRestartTransaction([
      ...restartLedgerCash,
      ...cashSheetRecords,
      ...allCashSheetRecords,
    ]),
    [restartLedgerCash, cashSheetRecords, allCashSheetRecords],
  );

  const countedAll = useMemo(
    () => splitCashAfterRestart(restartLedgerCash, restartInfo.restart).counted,
    [restartLedgerCash, restartInfo.restart],
  );

  const monthSplit = useMemo(
    () => splitCashAfterRestart(cashSheetRecords, restartInfo.restart),
    [cashSheetRecords, restartInfo.restart],
  );

  const globalSplit = useMemo(
    () => splitCashAfterRestart(allCashSheetRecords, restartInfo.restart),
    [allCashSheetRecords, restartInfo.restart],
  );

  const countedRecords = useMemo(() => {
    const list = isGlobalView
      ? countedAll
      : countedAll.filter((t) => inYearMonth(t.date, year, month));
    return [...list].sort((a, b) => String(b.date).localeCompare(String(a.date)));
  }, [isGlobalView, countedAll, year, month]);

  const historyRecords = useMemo(() => {
    const list = isGlobalView ? globalSplit.history : monthSplit.history;
    return [...list].sort((a, b) => String(b.date).localeCompare(String(a.date)));
  }, [isGlobalView, globalSplit.history, monthSplit.history]);

  const totals = useMemo(() => {
    if (isGlobalView) return computeRestartGlobalTotals(countedAll);
    return computeRestartMonthTotals(countedAll, year, month);
  }, [isGlobalView, countedAll, year, month]);

  const filterLabel = isGlobalView
    ? 'Vue globale — après régularisation du 17/09/2026'
    : monthBeforeRestart
      ? `Vue mois — ${periodLabel} — Hors calcul`
      : `Vue mois — ${periodLabel}`;

  function selectTableFilter(id) {
    setTableFilter(id);
  }

  const viewLoading = isGlobalView ? (allLoading || ledgerLoading) : (loading || ledgerLoading);
  const viewError = isGlobalView ? allError : error;
  const activeDayDate = viewMode === 'day' ? selectedDate : null;

  const isDayValidated = Boolean(dayValidation?.review_date);

  const canEditDay = viewMode === 'month' || !isDayValidated || superAdmin;

  useEffect(() => {
    if (!configured) return undefined;
    let cancelled = false;
    (async () => {
      setLedgerLoading(true);
      try {
        const txs = await listFinanceTransactionsPaged({ dateFrom: CASH_RESTART_DATE });
        if (!cancelled) setLedgerFromRestart(txs);
      } catch (err) {
        if (!cancelled) {
          console.warn('[CITYMO] ledger post-régularisation', err);
          setLedgerFromRestart([]);
        }
      } finally {
        if (!cancelled) setLedgerLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [configured, allReloadToken]);

  useEffect(() => {
    if (!isGlobalView || !configured) return undefined;
    let cancelled = false;
    (async () => {
      setAllLoading(true);
      setAllError('');
      try {
        const txs = await listAllFinanceTransactions();
        if (cancelled) return;
        setAllRecords(txs);
      } catch (err) {
        if (!cancelled) {
          setAllError(formatSupabaseError(err, 'Erreur chargement journal caisse.'));
          setAllRecords([]);
        }
      } finally {
        if (!cancelled) setAllLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [isGlobalView, configured, allReloadToken]);

  useEffect(() => {
    if (viewMode !== 'day' || (!isDG && !superAdmin)) {
      setDayValidation(null);
      return;
    }
    getCashDailyValidation(selectedDate)
      .then(setDayValidation)
      .catch((err) => {
        console.warn('[CITYMO] validation caisse jour', err);
        setDayValidation(null);
      });
  }, [viewMode, isDG, superAdmin, selectedDate, records.length]);

  useEffect(() => {
    if (!isDG && !superAdmin) return;
    getPendingCashValidation(now)
      .then(setPendingJ1Validation)
      .catch(() => setPendingJ1Validation(null));
  }, [isDG, superAdmin, records.length]);

  useEffect(() => {
    if (!configured) return undefined;
    let cancelled = false;
    (async () => {
      try {
        const r = await runRhPaymentsCashBackfill();
        let chargeDupes = { txCancelled: 0, chargesCancelled: 0 };
        try {
          chargeDupes = await dedupeAccidentalChargeCashDuplicates();
        } catch (dupErr) {
          console.warn('[CITYMO] dedupe charge → caisse', dupErr);
        }
        if (!cancelled) {
          if (r.total > 0 || r.removed > 0 || r.legacyPurged > 0 || chargeDupes.txCancelled > 0) {
            await reload();
            bumpAllReload();
          }
          if (chargeDupes.txCancelled > 0) {
            notify(`${chargeDupes.txCancelled} doublon(s) de dépense retirés de la caisse.`);
          }
          if (r.errors?.length) {
            notify(`${r.errors.length} erreur(s) sync RH — vérifiez RUN_FINANCE_TOUT_EN_UN.sql`);
          }
        }
      } catch (err) {
        if (!cancelled) {
          const msg = err?.message || String(err);
          if (err?.code === 'SCHEMA' || msg.includes('source_type')) {
            notify('Base Supabase incomplète — exécutez supabase/RUN_FINANCE_TOUT_EN_UN.sql puis Actualiser.');
          } else {
            console.warn('[CITYMO] backfill RH → caisse', err);
          }
        }
      }
      if (!cancelled) {
        auditRhFinanceSync().then(setRhAudit).catch(() => setRhAudit(null));
      }
    })();
    return () => { cancelled = true; };
  }, [configured]);

  function notify(msg) {
    setToast(msg);
    setTimeout(() => setToast(''), 4000);
  }

  async function handleReload() {
    setBackfilling(true);
    try {
      const r = await runRhPaymentsCashBackfill();
      await reload();
      bumpAllReload();
      const audit = await auditRhFinanceSync();
      setRhAudit(audit);
      if (r.total > 0) {
        notify(`${r.total} paiement(s) RH synchronisé(s) vers la caisse.`);
      } else if (r.legacyPurged > 0) {
        notify(`${r.legacyPurged} ancienne(s) ligne(s) hebdo supprimée(s) — affichage consolidé.`);
      } else if (r.removed > 0) {
        notify(`${r.removed} ligne(s) caisse supprimée(s) (paiements non payés).`);
      } else if ((audit.missingWorker || 0) + (audit.missingSubcontractor || 0) > 0) {
        notify(`${audit.missingWorker} ouvrier(s) et ${audit.missingSubcontractor} sous-traitant(s) payés sans ligne caisse — vérifiez les statuts « Payé ».`);
      } else if (r.errors?.length) {
        notify(`${r.errors.length} erreur(s) sync : ${r.errors[0]?.message || 'voir console'}`);
      }
    } catch (err) {
      const msg = err?.message || 'Erreur synchronisation paiements RH.';
      if (err?.code === 'SCHEMA' || err?.code === 'RLS' || msg.includes('source_type') || msg.includes('row-level security')) {
        notify('Exécutez supabase/RUN_SUPABASE_A_EXECUTER.sql dans Supabase SQL Editor, puis Actualiser.');
      } else {
        notify(msg);
      }
    } finally {
      setBackfilling(false);
    }
  }

  function isTxDayLocked(txDate) {
    if (!txDate || superAdmin) return false;
    if (viewMode !== 'day') return false;
    if (txDate !== selectedDate) return false;
    return isDayValidated;
  }

  function tryEditTx(t) {
    if (isAutoGeneratedTransaction(t)) {
      notify(getSourceModuleMessage(t));
      return;
    }
    if (isTxDayLocked(t.date)) {
      notify('Journée validée — modification impossible. Contactez le Super Admin.');
      return;
    }
    setEditTx(t);
    setShowModal(true);
  }

  async function tryRemoveTx(t) {
    if (isTxDayLocked(t.date)) {
      notify('Journée validée — suppression impossible. Contactez le Super Admin.');
      return;
    }
    const res = await removeTransaction(t.id);
    if (res?.success) bumpAllReload();
  }

  async function handleValidateDay() {
    const dateToValidate = activeDayDate;
    if (!dateToValidate) return;
    setValidating(true);
    try {
      const v = await validateCashDay(dateToValidate);
      setDayValidation(v);
      if (dateToValidate === yesterdayStr) {
        setPendingJ1Validation((p) => (p ? { ...p, validation: v, needsValidation: false } : p));
      }
      notify(`Caisse du ${formatDateFr(dateToValidate)} validée.`);
      const dayTotals = computeDailyCashTotals(cashSheetRecords, balance, dateToValidate);
      notifyCashReviewCompleted({
        reviewDate: dateToValidate,
        entrees: dayTotals.entreesJour,
        sorties: dayTotals.sortiesJour,
        soldeFin: dayTotals.soldeFinJournee,
      }).catch(() => {});
    } catch (err) {
      const msg = err?.message || 'Erreur validation.';
      if (msg.includes('row-level security') || msg.includes('daily_cash_reviews') || msg.includes('cash_daily_validations')) {
        notify('Erreur Supabase RLS — exécutez supabase/RUN_SUPABASE_A_EXECUTER.sql puis réessayez.');
      } else {
        notify(msg);
      }
    } finally {
      setValidating(false);
    }
  }

  async function handleUnlockDay() {
    if (!superAdmin) return;
    setUnlocking(true);
    try {
      await unlockCashDay(selectedDate);
      setDayValidation(null);
      notify(`Journée du ${formatDateShortFr(selectedDate)} déverrouillée.`);
    } catch (err) {
      notify(err?.message || 'Erreur déverrouillage.');
    } finally {
      setUnlocking(false);
    }
  }

  function openBalanceModal() {
    setBalForm({
      // Éditer la valeur stockée (amorce), pas le reliquat chaîné affiché.
      solde_initial: balance?.solde_initial_stored ?? balance?.solde_initial ?? '',
      alimentation: balance?.alimentation ?? 0,
      notes: balance?.notes ?? '',
      force_ouverture: Boolean(balance?.force_ouverture),
    });
    setShowBalance(true);
  }

  async function handleSaveTx(data) {
    if (isTxDayLocked(data.date)) {
      notify('Journée validée — enregistrement impossible.');
      return;
    }
    const payload = { ...data, ref: data.ref || genRef('CA') };
    const res = editTx
      ? await saveTransaction(payload, editTx.id)
      : await saveTransaction(payload);
    if (res.success) {
      setShowModal(false);
      setEditTx(null);
      bumpAllReload();
    }
  }

  async function handleSaveBalance(e) {
    e.preventDefault();
    const res = await saveBalance({
      solde_initial: parseFloat(balForm.solde_initial) || 0,
      // Conservé en base si historique, mais plus saisi à part (même nature que les entrées).
      alimentation: Number(balForm.alimentation) || Number(balance?.alimentation) || 0,
      notes: balForm.notes,
      force_ouverture: Boolean(balForm.force_ouverture),
    });
    if (res.success) {
      setShowBalance(false);
      bumpAllReload();
    }
  }

  const years = [];
  for (let y = now.getFullYear() - 2; y <= now.getFullYear() + 1; y++) years.push(y);

  function buildExportPayload() {
    return {
      year,
      month,
      periodLabel: isGlobalView
        ? 'Vue globale — après régularisation du 17/09/2026'
        : monthBeforeRestart
          ? `${periodLabel} — Hors calcul`
          : periodLabel,
      filename: isGlobalView
        ? 'feuille-caisse-globale'
        : `feuille-caisse-${year}-${String(month).padStart(2, '0')}`,
      soldeLabel: 'Solde caisse',
      transactions: countedRecords,
      historyTransactions: historyRecords,
      totals,
      balance: { solde_initial: totals.soldeInitial, notes: balance?.notes || '' },
    };
  }

  return (
    <div className="animate-fade-in">
      <div className="page-header flex-between finance-page-header">
        <div>
          <h1 className="page-title">FEUILLE DE CAISSE</h1>
          <p className="page-subtitle">
            <span className="finance-sub-hide-mobile">Journal trésorerie — paiements validés à la date réelle du paiement. </span>
            {isGlobalView
              ? <strong>Toutes périodes après le 17/09/2026</strong>
              : <>Mois <strong>{periodLabel}</strong>{monthBeforeRestart ? ' — Hors calcul' : ''}</>}
            {' · '}<strong>{filterLabel}</strong>
          </p>
        </div>
        <div className="finance-page-actions">
          <button type="button" className="btn btn-secondary btn-sm" onClick={() => exportCashSheetExcel(buildExportPayload())}>
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={() => exportCashSheetPdf(buildExportPayload())}
            title={`Export PDF CITYMO v${CASH_SHEET_PDF_VERSION}`}
          >
            <Download size={14} /> PDF
          </button>
          <button type="button" className="btn btn-secondary btn-sm" onClick={handleReload} disabled={viewLoading || backfilling}>
            <RefreshCw size={14} /> {backfilling ? 'Sync…' : 'Actualiser'}
          </button>
          {canManage && canEditDay && (
            <button type="button" className="btn btn-primary" onClick={() => { setEditTx(null); setShowModal(true); }}>
              <Plus size={15} /> Alimentation caisse
            </button>
          )}
        </div>
      </div>

      <div className="card finance-toolbar" style={{ marginBottom: 16, padding: '14px 20px' }}>
        <div className="finance-toolbar-inner">
          {!isGlobalView && (
            <>
              <select value={month} onChange={(e) => setMonth(Number(e.target.value))} style={{ ...SELECT_STYLE, maxWidth: 160 }}>
                {MOIS_OPTS.map((m) => <option key={m.v} value={m.v}>{m.l}</option>)}
              </select>
              <select value={year} onChange={(e) => setYear(Number(e.target.value))} style={{ ...SELECT_STYLE, maxWidth: 120 }}>
                {years.map((y) => <option key={y} value={y}>{y}</option>)}
              </select>
            </>
          )}
          <span className="finance-sub-hide-mobile" style={{ fontSize: '0.82rem', color: 'var(--text-3)' }}>
            {isGlobalView ? (
              <>
                Période : <strong>après le 17/09/2026</strong>
                {!viewLoading ? ` — ${countedRecords.length} op. comptabilisées` : ''}
              </>
            ) : (
              <>
                Période : <strong>{periodLabel}</strong>
                {isCurrentMonth ? ' (mois en cours)' : ''}
                {monthBeforeRestart ? ' — Hors calcul' : ''}
                {!loading ? ` — ${countedRecords.length} op. comptabilisées` : ''}
              </>
            )}
          </span>
          <div className="finance-toolbar-filters">
          {TABLE_FILTERS.map((f) => (
            <button
              key={f.id}
              type="button"
              className={`btn btn-sm ${tableFilter === f.id ? 'btn-primary' : 'btn-secondary'}`}
              onClick={() => selectTableFilter(f.id)}
            >
              {f.label}
            </button>
          ))}
          </div>
          {(!isCurrentMonth || isGlobalView) && (
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={() => { setYear(now.getFullYear()); setMonth(now.getMonth() + 1); setTableFilter('month'); }}
            >
              Revenir au mois en cours
            </button>
          )}
        </div>
      </div>

      {!configured && (
        <div className="card" style={{ marginBottom: 16, color: 'var(--red)', padding: 14, fontSize: '0.86rem' }}>
          Supabase non configuré. Ajoutez <code>VITE_SUPABASE_URL</code> et <code>VITE_SUPABASE_ANON_KEY</code> dans votre fichier <code>.env</code>, puis redémarrez l&apos;application.
        </div>
      )}
      {viewError && <div className="card" style={{ marginBottom: 16, color: 'var(--red)', padding: 14, fontSize: '0.86rem' }}>{viewError}</div>}
      {rhAudit && !rhAudit.error && rhAudit.schemaOk && ((rhAudit.missingWorker || 0) + (rhAudit.missingSubcontractor || 0) > 0) && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF3E0', border: '1px solid #FFB74D', color: '#E65100' }}>
          <strong>Sync RH incomplète :</strong>
          {' '}{rhAudit.missingWorker} paiement(s) ouvrier(s) et {rhAudit.missingSubcontractor} sous-traitant(s) payés sans ligne caisse.
          {' '}Passez le statut à « Payé » dans Paiement hebdo, puis cliquez <strong>Actualiser</strong>.
          {rhAudit.hint && <> — {rhAudit.hint}</>}
        </div>
      )}
      {rhAudit?.error && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF3E0', border: '1px solid #FFB74D', color: '#E65100' }}>
          {rhAudit.error}
          {rhAudit.hint && <> — {rhAudit.hint}</>}
        </div>
      )}
      {toast && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF8E1', border: '1px solid #FFE082', color: '#E65100' }}>
          {toast}
        </div>
      )}
      {restartInfo.ambiguous && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF8E1', border: '1px solid #FFE082', color: '#E65100' }}>
          Plusieurs écritures « régularisation caisse » le 17/09/2026. La plus ancienne (heure de création) sert de limite ; les suivantes restent en historique.
        </div>
      )}
      {!viewLoading && configured && !restartInfo.restart && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF8E1', border: '1px solid #FFE082', color: '#E65100' }}>
          Écriture « régularisation caisse » du 17/09/2026 introuvable. Les opérations de ce jour sont hors calcul (limite par date).
        </div>
      )}

      <div className="stat-grid finance-kpi-grid finance-kpi-strip">
        <KpiCard
          icon={<Wallet size={17} />}
          label="Reliquat"
          value={formatMAD(totals.soldeInitial)}
          color="grey"
          sub={isGlobalView
            ? 'départ 17/09/2026 à 0 MAD'
            : monthBeforeRestart
              ? 'Hors calcul — avant le 17/09/2026'
              : totals.soldeInitial
                ? 'report des opérations après régularisation'
                : 'départ 17/09/2026 à 0 MAD'}
        />
        <KpiCard
          icon={<Plus size={17} />}
          label="Alimentations / Entrées"
          value={formatMAD(totals.totalEntrees)}
          color="green"
          sub={isGlobalView
            ? 'entrées après régularisation'
            : monthBeforeRestart
              ? 'Hors calcul'
              : 'entrées de la période après régularisation'}
        />
        <KpiCard
          icon={<TrendingDown size={17} />}
          label="Sorties"
          value={formatMAD(totals.totalSorties)}
          color="red"
          sub={monthBeforeRestart && !isGlobalView ? 'Hors calcul' : undefined}
        />
        <KpiCard
          icon={<Wallet size={17} />}
          label="Solde caisse"
          value={formatMAD(totals.soldeMois)}
          color="blue"
          sub="reliquat + entrées − sorties"
        />
      </div>

      {viewLoading ? (
        <div style={{ textAlign: 'center', padding: 40 }}><Loader2 size={24} className="spin" /></div>
      ) : countedRecords.length === 0 && historyRecords.length === 0 ? (
        <div className="card">
          <EmptyState
            icon={<Wallet size={22} />}
            title={isGlobalView
              ? 'Aucune opération'
              : monthBeforeRestart
                ? `${periodLabel} — Hors calcul`
                : `Aucune opération — ${periodLabel}`}
            sub={configured && !viewError
              ? monthBeforeRestart && !isGlobalView
                ? 'Ce mois est antérieur à la régularisation du 17/09/2026.'
                : 'La prochaine alimentation après le 17/09/2026 apparaîtra ici.'
              : 'Connectez-vous et vérifiez la configuration Supabase.'}
            action={canManage && canEditDay ? 'Alimentation manuelle' : undefined}
            onAction={canManage && canEditDay ? () => setShowModal(true) : undefined}
          />
        </div>
      ) : (
        <>
          {!(monthBeforeRestart && !isGlobalView) && (
          <div className="card" style={{ padding: 0, marginBottom: historyRecords.length ? 16 : 0 }}>
            <div style={{ padding: '12px 16px 0', fontSize: '0.78rem', fontWeight: 700, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              Opérations comptabilisées
            </div>
            {countedRecords.length === 0 ? (
              <div style={{ padding: '16px 16px 20px', fontSize: '0.86rem', color: 'var(--text-3)' }}>
                Aucune opération après la régularisation du 17/09/2026. La caisse part de 0 MAD.
              </div>
            ) : (
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Source</th>
                      <th>Client / Fournisseur</th>
                      <th>Description</th>
                      <th>Sortie</th>
                      <th>Entrée</th>
                      <th>Paiement</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {countedRecords.map((t) => (
                      <CashSheetTxRow
                        key={t.id}
                        t={t}
                        history={false}
                        todayStr={todayStr}
                        canManage={canManage}
                        tryEditTx={tryEditTx}
                        tryRemoveTx={tryRemoveTx}
                        notify={notify}
                      />
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
          )}
          {historyRecords.length > 0 && (
            <div className="card" style={{ padding: 0 }}>
              <div style={{ padding: '12px 16px 0', fontSize: '0.78rem', fontWeight: 700, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                Historique <span style={{ fontWeight: 600, textTransform: 'none', letterSpacing: 0 }}>Hors calcul</span>
              </div>
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Source</th>
                      <th>Client / Fournisseur</th>
                      <th>Description</th>
                      <th>Sortie</th>
                      <th>Entrée</th>
                      <th>Paiement</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {historyRecords.map((t) => (
                      <CashSheetTxRow
                        key={t.id}
                        t={t}
                        history
                        todayStr={todayStr}
                        canManage={canManage}
                        tryEditTx={tryEditTx}
                        tryRemoveTx={tryRemoveTx}
                        notify={notify}
                      />
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}

      <Modal open={showModal} onClose={() => { setShowModal(false); setEditTx(null); }} title={editTx ? 'Modifier alimentation caisse' : 'Nouvelle alimentation caisse'}>
        <TxForm
          initial={editTx || { ...EMPTY_TX, date: viewMode === 'day' ? selectedDate : todayStr }}
          onSave={handleSaveTx}
          onCancel={() => { setShowModal(false); setEditTx(null); }}
          locked={isDayValidated && !superAdmin && (editTx?.date === selectedDate || (!editTx && viewMode === 'day'))}
        />
      </Modal>

      <Modal open={showBalance} onClose={() => setShowBalance(false)} title="Paramètres du mois" width={480}>
        <form onSubmit={handleSaveBalance}>
          <p style={{ fontSize: '0.82rem', color: 'var(--text-3)', margin: '0 0 12px' }}>
            Par défaut, le <strong>reliquat</strong> est le solde final du mois précédent (automatique).
            Cochez « ouverture forcée » pour démarrer ce mois sur le montant saisi, sans report.
            Les alimentations s’enregistrent via « + Alimentation caisse ».
          </p>
          <FField label="Reliquat (amorce / correction exceptionnelle)">
            <input type="number" step="0.01" value={balForm.solde_initial} onChange={(e) => setBalForm((p) => ({ ...p, solde_initial: e.target.value }))} style={INPUT_STYLE} />
          </FField>
          <label style={{ display: 'flex', alignItems: 'flex-start', gap: 8, marginBottom: 12, fontSize: '0.85rem', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={Boolean(balForm.force_ouverture)}
              onChange={(e) => setBalForm((p) => ({ ...p, force_ouverture: e.target.checked }))}
              style={{ marginTop: 3 }}
            />
            <span>
              <strong>Ouverture forcée</strong> — ignorer le report du mois précédent
              (ex. nouveau départ juillet à 0).
            </span>
          </label>
          <FField label="Notes">
            <textarea value={balForm.notes} onChange={(e) => setBalForm((p) => ({ ...p, notes: e.target.value }))} style={{ ...INPUT_STYLE, minHeight: 64 }} />
          </FField>
          <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
            <button type="button" className="btn btn-secondary" onClick={() => setShowBalance(false)}>Annuler</button>
            <button type="submit" className="btn btn-primary" disabled={saving}>Enregistrer</button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
