/**
 * FeuilleCaisse.jsx — Feuille de caisse (vue journalière + vue mensuelle)
 */
import { useState, useEffect, useMemo } from 'react';
import { Loader2, Plus, Download, FileSpreadsheet, Wallet, Edit2, Trash2, TrendingDown, RefreshCw, Bell, CheckCircle, Lock, Unlock, Calendar } from 'lucide-react';
import { useFinanceTransactions } from '../../hooks/useFinanceTransactions';
import { useAuth } from '../../hooks/useAuth';
import {
  TYPES_ENTREE, TYPES_SORTIE,
  isAutoGeneratedTransaction, getSourceBadgeLabel, getSourceModuleMessage,
  runRhPaymentsCashBackfill,
} from '../../services/finance/financeTransactions';
import { canManageCash, isDGUser } from '../../services/finance/cashAccess';
import { isSuperAdmin } from '../../services/rh/isSuperAdmin';
import {
  validateCashDay, getCashDailyValidation, unlockCashDay,
  getPendingCashValidation, todayIso, yesterdayIso, formatDateFr,
} from '../../services/finance/cashDailyValidation';
import { computeDailyCashTotals, formatDateShortFr } from '../../services/finance/cashDayTotals';
import { auditRhFinanceSync } from '../../services/finance/financeDiagnostics';
import { notifyCashReviewPending, notifyCashReviewCompleted } from '../../services/notifications/notificationEvents';
import { exportCashSheetPdf, CASH_SHEET_PDF_VERSION } from '../../services/finance/cashSheetPdf';
import { exportCashSheetExcel } from '../../services/finance/cashSheetExport';
import {
  INPUT_STYLE, SELECT_STYLE, MODES_PAIEMENT,
  KpiCard, EmptyState, Modal, FField, FRow,
  formatMAD, genRef,
} from './shared.jsx';

const MOIS_OPTS = [
  { v: 1, l: 'Janvier' }, { v: 2, l: 'Février' }, { v: 3, l: 'Mars' }, { v: 4, l: 'Avril' },
  { v: 5, l: 'Mai' }, { v: 6, l: 'Juin' }, { v: 7, l: 'Juillet' }, { v: 8, l: 'Août' },
  { v: 9, l: 'Septembre' }, { v: 10, l: 'Octobre' }, { v: 11, l: 'Novembre' }, { v: 12, l: 'Décembre' },
];

const MOIS_LABELS = ['', 'Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'];

const TABLE_FILTERS = [
  { id: 'today', label: "Aujourd'hui (J)" },
  { id: 'yesterday', label: 'Hier (J-1)' },
  { id: 'month', label: 'Vue mois' },
];

const EMPTY_TX = {
  date: '', sens: 'entree', type_operation: 'alimentation_caisse',
  contrepartie: '', description: '', montant: '', mode_paiement: 'Espèces',
};

function TxForm({ initial, onSave, onCancel, locked }) {
  const [form, setForm] = useState(initial || EMPTY_TX);
  const set = (k, v) => setForm((p) => ({ ...p, [k]: v }));
  const types = form.sens === 'entree' ? TYPES_ENTREE : TYPES_SORTIE;

  return (
    <form onSubmit={(e) => { e.preventDefault(); if (!locked) onSave({ ...form, montant: parseFloat(form.montant) || 0 }); }}>
      <FRow>
        <FField label="Date" required>
          <input type="date" value={form.date} onChange={(e) => set('date', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
        </FField>
        <FField label="Sens">
          <select value={form.sens} onChange={(e) => set('sens', e.target.value)} style={SELECT_STYLE} disabled={locked}>
            <option value="entree">Entrée de caisse</option>
            <option value="sortie">Sortie de caisse</option>
          </select>
        </FField>
        <FField label="Type">
          <select value={form.type_operation} onChange={(e) => set('type_operation', e.target.value)} style={SELECT_STYLE} disabled={locked}>
            {types.map((t) => <option key={t.value} value={t.value}>{t.label}</option>)}
          </select>
        </FField>
        <FField label="Montant (MAD)" required>
          <input type="number" min="0" step="0.01" value={form.montant} onChange={(e) => set('montant', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
        </FField>
      </FRow>
      <FRow>
        <FField label="Client / Fournisseur">
          <input value={form.contrepartie} onChange={(e) => set('contrepartie', e.target.value)} style={INPUT_STYLE} disabled={locked} />
        </FField>
        <FField label="Type paiement">
          <select value={form.mode_paiement} onChange={(e) => set('mode_paiement', e.target.value)} style={SELECT_STYLE} disabled={locked}>
            {MODES_PAIEMENT.map((m) => <option key={m} value={m}>{m}</option>)}
          </select>
        </FField>
      </FRow>
      <FField label="Description" required>
        <input value={form.description} onChange={(e) => set('description', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
      </FField>
      <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
        <button type="button" className="btn btn-secondary" onClick={onCancel}>Annuler</button>
        {!locked && <button type="submit" className="btn btn-primary">Enregistrer</button>}
      </div>
    </form>
  );
}

export default function FeuilleCaisse() {
  const now = new Date();
  const { user } = useAuth();
  const canManage = canManageCash(user);
  const isDG = isDGUser(user);
  const superAdmin = isSuperAdmin(user);

  const [tableFilter, setTableFilter] = useState('today');
  const [year, setYear] = useState(now.getFullYear());
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [showModal, setShowModal] = useState(false);
  const [editTx, setEditTx] = useState(null);
  const [showBalance, setShowBalance] = useState(false);
  const [balForm, setBalForm] = useState({ solde_initial: '', alimentation: '', notes: '' });
  const [validating, setValidating] = useState(false);
  const [unlocking, setUnlocking] = useState(false);
  const [backfilling, setBackfilling] = useState(false);
  const [toast, setToast] = useState('');
  const [dayValidation, setDayValidation] = useState(null);
  const [pendingJ1Validation, setPendingJ1Validation] = useState(null);
  const [rhAudit, setRhAudit] = useState(null);

  const {
    records, balance, totals, loading, saving, error, configured, reload,
    saveTransaction, removeTransaction, saveBalance,
  } = useFinanceTransactions(year, month);

  const todayStr = todayIso(now);
  const yesterdayStr = yesterdayIso(now);
  const isCurrentMonth = year === now.getFullYear() && month === now.getMonth() + 1;
  const periodLabel = `${MOIS_LABELS[month] || month} ${year}`;
  const viewMode = tableFilter === 'month' ? 'month' : 'day';
  const selectedDate = tableFilter === 'yesterday' ? yesterdayStr : todayStr;
  const filterLabel = tableFilter === 'today'
    ? `Aujourd'hui (J) — ${formatDateShortFr(todayStr)}`
    : tableFilter === 'yesterday'
      ? `Hier (J-1) — ${formatDateShortFr(yesterdayStr)}`
      : `Vue mois — ${periodLabel}`;

  function selectTableFilter(id) {
    if (id === 'today' || id === 'yesterday') {
      setYear(now.getFullYear());
      setMonth(now.getMonth() + 1);
    }
    setTableFilter(id);
  }

  useEffect(() => {
    if (!isCurrentMonth && tableFilter !== 'month') setTableFilter('month');
  }, [isCurrentMonth, year, month, tableFilter]);

  const sortedRecords = useMemo(
    () => [...records].sort((a, b) => String(b.date).localeCompare(String(a.date))),
    [records],
  );

  const displayedRecords = useMemo(() => {
    if (tableFilter === 'today') return sortedRecords.filter((t) => t.date === todayStr);
    if (tableFilter === 'yesterday') return sortedRecords.filter((t) => t.date === yesterdayStr);
    return sortedRecords;
  }, [sortedRecords, tableFilter, todayStr, yesterdayStr]);

  const activeDayDate = viewMode === 'day' ? selectedDate : null;
  const dailyTotals = useMemo(
    () => (activeDayDate ? computeDailyCashTotals(records, balance, activeDayDate) : null),
    [records, balance, activeDayDate],
  );

  const dayKpiLabel = tableFilter === 'yesterday' ? 'de la veille' : 'du jour';

  const isDayValidated = Boolean(dayValidation?.review_date);

  const canEditDay = viewMode === 'month' || !isDayValidated || superAdmin;

  const showValidationBlock = viewMode === 'day' && (isDG || superAdmin);

  useEffect(() => {
    if (viewMode !== 'day' || (!isDG && !superAdmin)) {
      setDayValidation(null);
      return;
    }
    getCashDailyValidation(selectedDate)
      .then(setDayValidation)
      .catch((err) => {
        console.warn('[CITYMO] validation caisse jour', err);
        setDayValidation(null);
      });
  }, [viewMode, isDG, superAdmin, selectedDate, records.length]);

  useEffect(() => {
    if (viewMode !== 'day' || isDayValidated || (!isDG && !superAdmin) || !dailyTotals) return;
    notifyCashReviewPending({
      reviewDate: selectedDate,
      opsCount: dailyTotals.dayCount,
    }).catch(() => {});
  }, [viewMode, isDayValidated, isDG, superAdmin, selectedDate, dailyTotals?.dayCount]);

  useEffect(() => {
    if (!isDG && !superAdmin) return;
    getPendingCashValidation(now)
      .then(setPendingJ1Validation)
      .catch(() => setPendingJ1Validation(null));
  }, [isDG, superAdmin, records.length]);

  useEffect(() => {
    if (!configured) return undefined;
    let cancelled = false;
    (async () => {
      try {
        const r = await runRhPaymentsCashBackfill();
        if (!cancelled) {
          if (r.total > 0 || r.removed > 0 || r.legacyPurged > 0) await reload();
          if (r.errors?.length) {
            notify(`${r.errors.length} erreur(s) sync RH — vérifiez RUN_FINANCE_TOUT_EN_UN.sql`);
          }
        }
      } catch (err) {
        if (!cancelled) {
          const msg = err?.message || String(err);
          if (err?.code === 'SCHEMA' || msg.includes('source_type')) {
            notify('Base Supabase incomplète — exécutez supabase/RUN_FINANCE_TOUT_EN_UN.sql puis Actualiser.');
          } else {
            console.warn('[CITYMO] backfill RH → caisse', err);
          }
        }
      }
      if (!cancelled) {
        auditRhFinanceSync().then(setRhAudit).catch(() => setRhAudit(null));
      }
    })();
    return () => { cancelled = true; };
  }, [configured]);

  function notify(msg) {
    setToast(msg);
    setTimeout(() => setToast(''), 4000);
  }

  async function handleReload() {
    setBackfilling(true);
    try {
      const r = await runRhPaymentsCashBackfill();
      await reload();
      const audit = await auditRhFinanceSync();
      setRhAudit(audit);
      if (r.total > 0) {
        notify(`${r.total} paiement(s) RH synchronisé(s) vers la caisse.`);
      } else if (r.legacyPurged > 0) {
        notify(`${r.legacyPurged} ancienne(s) ligne(s) hebdo supprimée(s) — affichage consolidé.`);
      } else if (r.removed > 0) {
        notify(`${r.removed} ligne(s) caisse supprimée(s) (paiements non payés).`);
      } else if ((audit.missingWorker || 0) + (audit.missingSubcontractor || 0) > 0) {
        notify(`${audit.missingWorker} ouvrier(s) et ${audit.missingSubcontractor} sous-traitant(s) payés sans ligne caisse — vérifiez les statuts « Payé ».`);
      } else if (r.errors?.length) {
        notify(`${r.errors.length} erreur(s) de synchronisation.`);
      }
    } catch (err) {
      const msg = err?.message || 'Erreur synchronisation paiements RH.';
      if (err?.code === 'SCHEMA' || msg.includes('source_type')) {
        notify('Exécutez supabase/RUN_FINANCE_TOUT_EN_UN.sql dans Supabase SQL Editor, puis Actualiser.');
      } else {
        notify(msg);
      }
    } finally {
      setBackfilling(false);
    }
  }

  function isTxDayLocked(txDate) {
    if (!txDate || superAdmin) return false;
    if (viewMode === 'month') return false;
    if (txDate !== selectedDate) return false;
    return isDayValidated;
  }

  function tryEditTx(t) {
    if (isAutoGeneratedTransaction(t)) {
      notify(getSourceModuleMessage(t));
      return;
    }
    if (isTxDayLocked(t.date)) {
      notify('Journée validée — modification impossible. Contactez le Super Admin.');
      return;
    }
    setEditTx(t);
    setShowModal(true);
  }

  async function tryRemoveTx(t) {
    if (isTxDayLocked(t.date)) {
      notify('Journée validée — suppression impossible. Contactez le Super Admin.');
      return;
    }
    await removeTransaction(t.id);
  }

  async function handleValidateDay() {
    const dateToValidate = activeDayDate;
    if (!dateToValidate) return;
    setValidating(true);
    try {
      const v = await validateCashDay(dateToValidate);
      setDayValidation(v);
      if (dateToValidate === yesterdayStr) {
        setPendingJ1Validation((p) => (p ? { ...p, validation: v, needsValidation: false } : p));
      }
      notify(`Caisse du ${formatDateFr(dateToValidate)} validée.`);
      const totals = computeDailyCashTotals(records, balance, dateToValidate);
      notifyCashReviewCompleted({
        reviewDate: dateToValidate,
        entrees: totals.entreesJour,
        sorties: totals.sortiesJour,
        soldeFin: totals.soldeFinJournee,
      }).catch(() => {});
    } catch (err) {
      const msg = err?.message || 'Erreur validation.';
      if (msg.includes('row-level security') || msg.includes('daily_cash_reviews') || msg.includes('cash_daily_validations')) {
        notify('Erreur Supabase RLS — exécutez supabase/RUN_FINANCE_TOUT_EN_UN.sql puis réessayez.');
      } else {
        notify(msg);
      }
    } finally {
      setValidating(false);
    }
  }

  async function handleUnlockDay() {
    if (!superAdmin) return;
    setUnlocking(true);
    try {
      await unlockCashDay(selectedDate);
      setDayValidation(null);
      notify(`Journée du ${formatDateShortFr(selectedDate)} déverrouillée.`);
    } catch (err) {
      notify(err?.message || 'Erreur déverrouillage.');
    } finally {
      setUnlocking(false);
    }
  }

  function openBalanceModal() {
    setBalForm({
      solde_initial: balance?.solde_initial ?? '',
      alimentation: balance?.alimentation ?? '',
      notes: balance?.notes ?? '',
    });
    setShowBalance(true);
  }

  async function handleSaveTx(data) {
    if (isTxDayLocked(data.date)) {
      notify('Journée validée — enregistrement impossible.');
      return;
    }
    const payload = { ...data, ref: data.ref || genRef('CA') };
    const res = editTx
      ? await saveTransaction(payload, editTx.id)
      : await saveTransaction(payload);
    if (res.success) { setShowModal(false); setEditTx(null); }
  }

  async function handleSaveBalance(e) {
    e.preventDefault();
    const res = await saveBalance({
      solde_initial: parseFloat(balForm.solde_initial) || 0,
      alimentation: parseFloat(balForm.alimentation) || 0,
      notes: balForm.notes,
    });
    if (res.success) setShowBalance(false);
  }

  const years = [];
  for (let y = now.getFullYear() - 2; y <= now.getFullYear() + 1; y++) years.push(y);

  const showJ1ValidationBanner = (isDG || superAdmin)
    && pendingJ1Validation?.needsValidation
    && viewMode === 'day'
    && tableFilter === 'yesterday';

  return (
    <div className="animate-fade-in">
      <div className="page-header flex-between" style={{ flexWrap: 'wrap', gap: 10 }}>
        <div>
          <h1 className="page-title">FEUILLE DE CAISSE</h1>
          <p className="page-subtitle">
            Journal trésorerie — paiements validés à la date réelle du paiement.
            {viewMode === 'day'
              ? <> Validation DG : <strong>{formatDateShortFr(selectedDate)}</strong>.</>
              : <> Synthèse mensuelle — <strong>{periodLabel}</strong>.</>}
            {' '}<strong>{filterLabel}</strong>
          </p>
        </div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          <button type="button" className="btn btn-secondary btn-sm" onClick={() => exportCashSheetExcel({ year, month, transactions: records, totals })}>
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={() => exportCashSheetPdf({ year, month, transactions: records, totals, balance })}
            title={`Export PDF CITYMO v${CASH_SHEET_PDF_VERSION}`}
          >
            <Download size={14} /> PDF
          </button>
          {canManage && (
            <button type="button" className="btn btn-secondary btn-sm" onClick={openBalanceModal}>
              <Wallet size={14} /> Solde initial
            </button>
          )}
          <button type="button" className="btn btn-secondary btn-sm" onClick={handleReload} disabled={loading || backfilling}>
            <RefreshCw size={14} /> {backfilling ? 'Sync…' : 'Actualiser'}
          </button>
          {canManage && canEditDay && (
            <button type="button" className="btn btn-primary" onClick={() => { setEditTx(null); setShowModal(true); }}>
              <Plus size={15} /> Alimentation / Opération
            </button>
          )}
        </div>
      </div>

      <div className="card" style={{ marginBottom: 16, padding: '14px 20px' }}>
        <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}>
          <select value={month} onChange={(e) => setMonth(Number(e.target.value))} style={{ ...SELECT_STYLE, maxWidth: 160 }}>
            {MOIS_OPTS.map((m) => <option key={m.v} value={m.v}>{m.l}</option>)}
          </select>
          <select value={year} onChange={(e) => setYear(Number(e.target.value))} style={{ ...SELECT_STYLE, maxWidth: 120 }}>
            {years.map((y) => <option key={y} value={y}>{y}</option>)}
          </select>
          <span style={{ fontSize: '0.82rem', color: 'var(--text-3)' }}>
            Période : <strong>{periodLabel}</strong>
            {isCurrentMonth ? ' (mois en cours)' : ''}
            {!loading && records.length > 0 ? ` — ${records.length} op. ce mois` : ''}
          </span>
          {TABLE_FILTERS.map((f) => (
            <button
              key={f.id}
              type="button"
              className={`btn btn-sm ${tableFilter === f.id ? 'btn-primary' : 'btn-secondary'}`}
              onClick={() => selectTableFilter(f.id)}
              disabled={!isCurrentMonth && f.id !== 'month'}
              title={!isCurrentMonth && f.id !== 'month' ? 'J et J-1 disponibles sur le mois en cours' : undefined}
            >
              {f.label}
            </button>
          ))}
          {!isCurrentMonth && (
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={() => { setYear(now.getFullYear()); setMonth(now.getMonth() + 1); setTableFilter('today'); }}
            >
              Revenir au mois en cours
            </button>
          )}
          {viewMode === 'day' && dailyTotals && (
            <span style={{ fontSize: '0.82rem', color: 'var(--text-3)' }}>
              {dailyTotals.dayCount} op. {dayKpiLabel}
            </span>
          )}
          {viewMode === 'month' && (
            <span style={{ fontSize: '0.82rem', color: 'var(--text-3)' }}>
              {displayedRecords.length} op. sur le mois
            </span>
          )}
        </div>
      </div>

      {!configured && (
        <div className="card" style={{ marginBottom: 16, color: 'var(--red)', padding: 14, fontSize: '0.86rem' }}>
          Supabase non configuré. Ajoutez <code>VITE_SUPABASE_URL</code> et <code>VITE_SUPABASE_ANON_KEY</code> dans votre fichier <code>.env</code>, puis redémarrez l&apos;application.
        </div>
      )}
      {error && <div className="card" style={{ marginBottom: 16, color: 'var(--red)', padding: 14, fontSize: '0.86rem' }}>{error}</div>}
      {rhAudit && !rhAudit.error && rhAudit.schemaOk && ((rhAudit.missingWorker || 0) + (rhAudit.missingSubcontractor || 0) > 0) && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF3E0', border: '1px solid #FFB74D', color: '#E65100' }}>
          <strong>Sync RH incomplète :</strong>
          {' '}{rhAudit.missingWorker} paiement(s) ouvrier(s) et {rhAudit.missingSubcontractor} sous-traitant(s) payés sans ligne caisse.
          {' '}Passez le statut à « Payé » dans Paiement hebdo, puis cliquez <strong>Actualiser</strong>.
          {rhAudit.hint && <> — {rhAudit.hint}</>}
        </div>
      )}
      {rhAudit?.error && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF3E0', border: '1px solid #FFB74D', color: '#E65100' }}>
          {rhAudit.error}
          {rhAudit.hint && <> — {rhAudit.hint}</>}
        </div>
      )}
      {toast && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF8E1', border: '1px solid #FFE082', color: '#E65100' }}>
          {toast}
        </div>
      )}

      {showJ1ValidationBanner && !isDayValidated && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF3E0', border: '1px solid #FFB74D', color: '#E65100' }}>
          <strong>Validation J-1 en attente</strong> — clôturez la caisse d&apos;hier ({formatDateShortFr(yesterdayStr)}).
        </div>
      )}

      {showValidationBlock && !isDayValidated && dailyTotals && (
        <div className="card" style={{ marginBottom: 16, padding: '14px 18px', display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12, background: '#E3F2FD', border: '1px solid #90CAF9' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10, fontSize: '0.88rem', maxWidth: 720 }}>
            <Bell size={18} style={{ color: '#1565C0', flexShrink: 0, marginTop: 2 }} />
            <span>
              <strong>Validation caisse {tableFilter === 'yesterday' ? 'J-1' : 'J'} requise.</strong>
              {' '}Veuillez valider la caisse du{' '}
              <strong>{formatDateFr(selectedDate)}</strong>.
              {dailyTotals.dayCount > 0 && (
                <> — {dailyTotals.dayCount} opération(s) : entrées {formatMAD(dailyTotals.entreesJour)}, sorties {formatMAD(dailyTotals.sortiesJour)}.</>
              )}
              {dailyTotals.dayCount === 0 && ' — Aucune opération enregistrée ce jour-là (validation de clôture).'}
            </span>
          </div>
          <button type="button" className="btn btn-primary btn-sm" onClick={handleValidateDay} disabled={validating}>
            {validating ? <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} /> : <CheckCircle size={14} />}
            {' '}Valider {tableFilter === 'yesterday' ? 'J-1' : 'J'}
          </button>
        </div>
      )}

      {showValidationBlock && isDayValidated && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 18px', display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12, background: '#E8F5E9', border: '1px solid #A5D6A7' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.88rem', color: '#2E7D32' }}>
            <CheckCircle size={18} />
            <span className="badge badge-green" style={{ fontSize: '0.75rem' }}>Journée validée</span>
            <span>{formatDateFr(selectedDate)}</span>
            {!canEditDay && (
              <span style={{ display: 'flex', alignItems: 'center', gap: 4, color: 'var(--text-3)', fontSize: '0.82rem' }}>
                <Lock size={14} /> Modifications verrouillées
              </span>
            )}
          </div>
          {superAdmin && (
            <button type="button" className="btn btn-secondary btn-sm" onClick={handleUnlockDay} disabled={unlocking}>
              {unlocking ? <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} /> : <Unlock size={14} />}
              {' '}Déverrouiller
            </button>
          )}
        </div>
      )}

      {viewMode === 'day' && dailyTotals ? (
        <div className="stat-grid finance-kpi-grid" style={{ marginBottom: 20 }}>
          <KpiCard icon={<Wallet size={17} />} label={`Solde début ${dayKpiLabel}`} value={formatMAD(dailyTotals.soldeDebutJournee)} color="grey" sub="solde cumulé avant cette date" />
          <KpiCard icon={<Plus size={17} />} label={`Entrées ${dayKpiLabel}`} value={formatMAD(dailyTotals.entreesJour)} color="green" />
          <KpiCard icon={<TrendingDown size={17} />} label={`Sorties ${dayKpiLabel}`} value={formatMAD(dailyTotals.sortiesJour)} color="red" />
          <KpiCard icon={<Wallet size={17} />} label={`Solde fin ${dayKpiLabel}`} value={formatMAD(dailyTotals.soldeFinJournee)} color="blue" sub="début + entrées − sorties" />
        </div>
      ) : viewMode === 'month' ? (
        <div className="stat-grid finance-kpi-grid" style={{ marginBottom: 20 }}>
          <KpiCard icon={<Wallet size={17} />} label="Solde initial" value={formatMAD(totals.soldeInitial)} color="grey" />
          <KpiCard icon={<Plus size={17} />} label="Alimentation" value={formatMAD(totals.alimentation)} color="purple" />
          <KpiCard icon={<Plus size={17} />} label="Total entrées" value={formatMAD(totals.totalEntrees)} color="green" />
          <KpiCard icon={<TrendingDown size={17} />} label="Total sorties" value={formatMAD(totals.totalSorties)} color="red" />
          <KpiCard icon={<Wallet size={17} />} label="Solde caisse du mois" value={formatMAD(totals.soldeMois)} color="blue" sub="solde_initial + alimentation + entrées − sorties" />
        </div>
      ) : null}

      {loading ? (
        <div style={{ textAlign: 'center', padding: 40 }}><Loader2 size={24} className="spin" /></div>
      ) : displayedRecords.length === 0 ? (
        <div className="card">
          <EmptyState
            icon={<Wallet size={22} />}
            title={viewMode === 'day'
              ? `Aucune opération — ${formatDateShortFr(selectedDate)}`
              : `Aucune opération — ${periodLabel}`}
            sub={configured && !error
              ? viewMode === 'month'
                ? 'Historique complet du mois. Passez en vue jour pour la validation quotidienne.'
                : 'Validez un paiement dans Paiement hebdo ou Sous-traitants — la sortie s\'ajoute automatiquement à la date du paiement.'
              : 'Connectez-vous et vérifiez la configuration Supabase.'}
            action={canManage && canEditDay ? 'Alimentation manuelle' : undefined}
            onAction={canManage && canEditDay ? () => setShowModal(true) : undefined}
          />
        </div>
      ) : (
        <div className="card" style={{ padding: 0 }}>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Source</th>
                  <th>Client / Fournisseur</th>
                  <th>Description</th>
                  <th>Sortie</th>
                  <th>Entrée</th>
                  <th>Paiement</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {displayedRecords.map((t) => {
                  const isAuto = isAutoGeneratedTransaction(t);
                  const badge = getSourceBadgeLabel(t);
                  const isSelectedDay = viewMode === 'day' && t.date === selectedDate;
                  const rowLocked = isSelectedDay && isDayValidated && !superAdmin && viewMode === 'day';
                  return (
                  <tr key={t.id} style={isSelectedDay ? { background: '#E8F5E9' } : undefined}>
                    <td data-label="Date">
                      {t.date}
                      {t.date === todayStr && (
                        <span className="badge badge-green" style={{ marginLeft: 6, fontSize: '0.65rem' }}>J</span>
                      )}
                    </td>
                    <td data-label="Source">
                      <span className={`badge ${isAuto ? 'badge-blue' : 'badge-grey'}`} style={{ fontSize: '0.72rem', whiteSpace: 'nowrap' }}>
                        {badge}
                      </span>
                    </td>
                    <td data-label="Contrepartie">{t.contrepartie || '—'}</td>
                    <td data-label="Description">{t.description}</td>
                    <td data-label="Sortie" style={{ color: 'var(--red)', fontWeight: 600 }}>
                      {t.sens === 'sortie' ? formatMAD(t.montant) : '—'}
                    </td>
                    <td data-label="Entrée" style={{ color: '#2E7D32', fontWeight: 600 }}>
                      {t.sens === 'entree' ? formatMAD(t.montant) : '—'}
                    </td>
                    <td data-label="Paiement">{t.mode_paiement}</td>
                    <td data-label="Actions">
                      {!isAuto && canManage && !rowLocked && (
                        <div style={{ display: 'flex', gap: 6 }}>
                          <button type="button" className="btn btn-ghost btn-sm" onClick={() => tryEditTx(t)}><Edit2 size={13} /></button>
                          <button type="button" className="btn btn-ghost btn-sm" style={{ color: 'var(--red)' }} onClick={() => tryRemoveTx(t)}><Trash2 size={13} /></button>
                        </div>
                      )}
                      {!isAuto && canManage && rowLocked && (
                        <Lock size={14} style={{ opacity: 0.4 }} title="Journée validée" />
                      )}
                      {isAuto && (
                        <button type="button" className="btn btn-ghost btn-sm" title="Lecture seule" onClick={() => notify(getSourceModuleMessage(t))}>
                          <Edit2 size={13} style={{ opacity: 0.35 }} />
                        </button>
                      )}
                    </td>
                  </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <Modal open={showModal} onClose={() => { setShowModal(false); setEditTx(null); }} title={editTx ? 'Modifier opération' : 'Nouvelle opération caisse'}>
        <TxForm
          initial={editTx || { ...EMPTY_TX, date: viewMode === 'day' ? selectedDate : todayStr }}
          onSave={handleSaveTx}
          onCancel={() => { setShowModal(false); setEditTx(null); }}
          locked={isDayValidated && !superAdmin && (editTx?.date === selectedDate || (!editTx && viewMode === 'day'))}
        />
      </Modal>

      <Modal open={showBalance} onClose={() => setShowBalance(false)} title="Paramètres du mois" width={480}>
        <form onSubmit={handleSaveBalance}>
          <FRow>
            <FField label="Solde caisse mois précédent">
              <input type="number" step="0.01" value={balForm.solde_initial} onChange={(e) => setBalForm((p) => ({ ...p, solde_initial: e.target.value }))} style={INPUT_STYLE} />
            </FField>
            <FField label="Alimentation caisse">
              <input type="number" step="0.01" value={balForm.alimentation} onChange={(e) => setBalForm((p) => ({ ...p, alimentation: e.target.value }))} style={INPUT_STYLE} />
            </FField>
          </FRow>
          <FField label="Notes">
            <textarea value={balForm.notes} onChange={(e) => setBalForm((p) => ({ ...p, notes: e.target.value }))} style={{ ...INPUT_STYLE, minHeight: 64 }} />
          </FField>
          <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
            <button type="button" className="btn btn-secondary" onClick={() => setShowBalance(false)}>Annuler</button>
            <button type="submit" className="btn btn-primary" disabled={saving}>Enregistrer</button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
