/**
 * FeuilleCaisse.jsx — Feuille de caisse (vue mensuelle + vue globale)
 */
import { useState, useEffect, useMemo } from 'react';
import { Loader2, Plus, Download, FileSpreadsheet, Wallet, Edit2, Trash2, TrendingDown, RefreshCw, Lock, Calendar } from 'lucide-react';
import { useFinanceTransactions } from '../../hooks/useFinanceTransactions';
import { useAuth } from '../../hooks/useAuth';
import {
  isAutoGeneratedTransaction, getSourceBadgeLabel, getSourceModuleMessage,
  runRhPaymentsCashBackfill,
  computeCashTotals,
  listAllFinanceTransactions,
} from '../../services/finance/financeTransactions';
import { resolveEffectiveBalance } from '../../services/finance/cashMonthlyBalances';
import { formatSupabaseError } from '../../services/supabase/formatError';
import { listProjectsForSelect } from '../../services/projects/projects';
import { canManageCash, isDGUser } from '../../services/finance/cashAccess';
import { isSuperAdmin } from '../../services/rh/isSuperAdmin';
import {
  validateCashDay, getCashDailyValidation, unlockCashDay,
  getPendingCashValidation, todayIso, yesterdayIso, formatDateFr,
} from '../../services/finance/cashDailyValidation';
import { computeDailyCashTotals, formatDateShortFr } from '../../services/finance/cashDayTotals';
import { consolidateCashSheetTransactions } from '../../services/finance/cashSheetDisplay';
import { auditRhFinanceSync } from '../../services/finance/financeDiagnostics';
import { notifyCashReviewCompleted } from '../../services/notifications/notificationEvents';
import { exportCashSheetPdf, CASH_SHEET_PDF_VERSION } from '../../services/finance/cashSheetPdf';
import { exportCashSheetExcel } from '../../services/finance/cashSheetExport';
import {
  INPUT_STYLE, SELECT_STYLE,
  KpiCard, EmptyState, Modal, FField, FRow,
  formatMAD, genRef,
} from './shared.jsx';

const MOIS_OPTS = [
  { v: 1, l: 'Janvier' }, { v: 2, l: 'Février' }, { v: 3, l: 'Mars' }, { v: 4, l: 'Avril' },
  { v: 5, l: 'Mai' }, { v: 6, l: 'Juin' }, { v: 7, l: 'Juillet' }, { v: 8, l: 'Août' },
  { v: 9, l: 'Septembre' }, { v: 10, l: 'Octobre' }, { v: 11, l: 'Novembre' }, { v: 12, l: 'Décembre' },
];

const MOIS_LABELS = ['', 'Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'];

const TABLE_FILTERS = [
  { id: 'month', label: 'Vue mois' },
  { id: 'since_reset', label: 'Depuis la régularisation' },
  { id: 'all', label: 'Vue globale' },
];

function isRegularisationCaisse(tx) {
  const raw = String(tx?.description || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
  return raw.includes('regularisation caisse');
}

function lastRegularisationDate(transactions) {
  let latest = '';
  (transactions || []).forEach((t) => {
    if (!isRegularisationCaisse(t)) return;
    const d = String(t.date || '');
    if (d && d > latest) latest = d;
  });
  return latest || null;
}

const EMPTY_TX = {
  date: '', sens: 'entree', type_operation: 'alimentation_caisse',
  project_id: '', description: '', montant: '', mode_paiement: 'Espèces',
};

function TxForm({ initial, onSave, onCancel, locked }) {
  const [form, setForm] = useState(initial || EMPTY_TX);
  const [projects, setProjects] = useState([]);
  const set = (k, v) => setForm((p) => ({ ...p, [k]: v }));

  useEffect(() => {
    let cancelled = false;
    listProjectsForSelect()
      .then((rows) => { if (!cancelled) setProjects(rows || []); })
      .catch(() => { if (!cancelled) setProjects([]); });
    return () => { cancelled = true; };
  }, []);

  return (
    <form onSubmit={(e) => {
      e.preventDefault();
      if (locked) return;
      onSave({
        ...form,
        sens: form.sens || 'entree',
        type_operation: form.type_operation || 'alimentation_caisse',
        mode_paiement: form.mode_paiement || 'Espèces',
        montant: parseFloat(form.montant) || 0,
        project_id: form.project_id || null,
      });
    }}
    >
      <FRow>
        <FField label="Date" required>
          <input type="date" value={form.date} onChange={(e) => set('date', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
        </FField>
        <FField label="Type">
          <input value="Alimentation caisse" style={{ ...INPUT_STYLE, background: 'var(--surface-2)' }} readOnly disabled />
        </FField>
        <FField label="Montant (MAD)" required>
          <input type="number" min="0" step="0.01" value={form.montant} onChange={(e) => set('montant', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
        </FField>
        <FField label="Projet lié">
          <select value={form.project_id || ''} onChange={(e) => set('project_id', e.target.value)} style={SELECT_STYLE} disabled={locked}>
            <option value="">— Aucun —</option>
            {projects.map((p) => (
              <option key={p.id} value={p.id}>{p.nom || p.ref || p.id}</option>
            ))}
          </select>
        </FField>
      </FRow>
      <FField label="Description" required>
        <input value={form.description} onChange={(e) => set('description', e.target.value)} style={INPUT_STYLE} required disabled={locked} />
      </FField>
      <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
        <button type="button" className="btn btn-secondary" onClick={onCancel}>Annuler</button>
        {!locked && <button type="submit" className="btn btn-primary">Enregistrer</button>}
      </div>
    </form>
  );
}

export default function FeuilleCaisse() {
  const now = new Date();
  const { user } = useAuth();
  const canManage = canManageCash(user);
  const isDG = isDGUser(user);
  const superAdmin = isSuperAdmin(user);

  const [tableFilter, setTableFilter] = useState('month');
  const [year, setYear] = useState(now.getFullYear());
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [allRecords, setAllRecords] = useState([]);
  const [allBalance, setAllBalance] = useState(null);
  const [allLoading, setAllLoading] = useState(false);
  const [allError, setAllError] = useState('');
  const [allReloadToken, setAllReloadToken] = useState(0);
  const [showModal, setShowModal] = useState(false);
  const [editTx, setEditTx] = useState(null);
  const [showBalance, setShowBalance] = useState(false);
  const [balForm, setBalForm] = useState({
    solde_initial: '',
    alimentation: '',
    notes: '',
    force_ouverture: false,
  });
  const [validating, setValidating] = useState(false);
  const [unlocking, setUnlocking] = useState(false);
  const [backfilling, setBackfilling] = useState(false);
  const [toast, setToast] = useState('');
  const [dayValidation, setDayValidation] = useState(null);
  const [pendingJ1Validation, setPendingJ1Validation] = useState(null);
  const [rhAudit, setRhAudit] = useState(null);

  const {
    records, balance, loading, saving, error, configured, reload,
    saveTransaction, removeTransaction, saveBalance,
  } = useFinanceTransactions(year, month);

  const todayStr = todayIso(now);
  const yesterdayStr = yesterdayIso(now);
  const isCurrentMonth = year === now.getFullYear() && month === now.getMonth() + 1;
  const isGlobalView = tableFilter === 'all';
  const isSinceResetView = tableFilter === 'since_reset';
  const periodLabel = `${MOIS_LABELS[month] || month} ${year}`;
  const viewMode = isGlobalView ? 'all' : 'month';
  const selectedDate = todayStr;

  function bumpAllReload() {
    setAllReloadToken((n) => n + 1);
  }

  const cashSheetRecords = useMemo(
    () => consolidateCashSheetTransactions(records),
    [records],
  );

  /** KPI mois : même formule que le hook, mais uniquement sur mouvements espèces. */
  const totals = useMemo(
    () => computeCashTotals(cashSheetRecords, balance),
    [cashSheetRecords, balance],
  );

  const allCashSheetRecords = useMemo(
    () => consolidateCashSheetTransactions(allRecords),
    [allRecords],
  );

  const allTotals = useMemo(
    () => computeCashTotals(allCashSheetRecords, allBalance),
    [allCashSheetRecords, allBalance],
  );

  const sortedRecords = useMemo(
    () => [...cashSheetRecords].sort((a, b) => String(b.date).localeCompare(String(a.date))),
    [cashSheetRecords],
  );

  const regularisationDate = useMemo(
    () => lastRegularisationDate(cashSheetRecords),
    [cashSheetRecords],
  );

  const sinceResetRecords = useMemo(() => {
    if (!regularisationDate) return [];
    return cashSheetRecords.filter((t) => String(t.date || '') > regularisationDate);
  }, [cashSheetRecords, regularisationDate]);

  const sinceResetTotals = useMemo(
    () => computeCashTotals(sinceResetRecords, { solde_initial: 0 }),
    [sinceResetRecords],
  );

  const displayedRecords = useMemo(() => {
    if (isGlobalView) {
      return [...allCashSheetRecords].sort((a, b) => String(b.date).localeCompare(String(a.date)));
    }
    if (isSinceResetView) {
      return [...sinceResetRecords].sort((a, b) => String(b.date).localeCompare(String(a.date)));
    }
    return sortedRecords;
  }, [isGlobalView, isSinceResetView, allCashSheetRecords, sinceResetRecords, sortedRecords]);

  const viewTotals = isGlobalView ? allTotals : (isSinceResetView ? sinceResetTotals : totals);
  const regularisationLabel = regularisationDate ? formatDateShortFr(regularisationDate) : '';
  const filterLabel = isGlobalView
    ? 'Vue globale — toutes les opérations'
    : isSinceResetView
      ? `Depuis la régularisation — ${regularisationLabel}`
      : `Vue mois — ${periodLabel}`;

  function selectTableFilter(id) {
    if (id === 'since_reset' && !regularisationDate) return;
    setTableFilter(id);
  }

  const viewLoading = isGlobalView ? allLoading : loading;
  const viewError = isGlobalView ? allError : error;
  const activeDayDate = viewMode === 'day' ? selectedDate : null;

  const isDayValidated = Boolean(dayValidation?.review_date);

  const canEditDay = viewMode === 'month' || !isDayValidated || superAdmin;

  useEffect(() => {
    if (tableFilter === 'since_reset' && !regularisationDate) setTableFilter('month');
  }, [tableFilter, regularisationDate]);

  useEffect(() => {
    if (!isGlobalView || !configured) return undefined;
    let cancelled = false;
    (async () => {
      setAllLoading(true);
      setAllError('');
      try {
        const txs = await listAllFinanceTransactions();
        if (cancelled) return;
        const cash = consolidateCashSheetTransactions(txs);
        let openingBal = { solde_initial: 0 };
        const firstDate = cash.reduce((min, t) => {
          const d = String(t.date || '');
          if (!d) return min;
          return !min || d < min ? d : min;
        }, '');
        if (firstDate.length >= 7) {
          const y = Number(firstDate.slice(0, 4));
          const m = Number(firstDate.slice(5, 7));
          if (y && m) {
            try {
              openingBal = await resolveEffectiveBalance(y, m);
            } catch (reliquatErr) {
              console.warn('[CITYMO] reliquat vue globale indisponible', reliquatErr);
              openingBal = { solde_initial: 0 };
            }
          }
        }
        if (cancelled) return;
        setAllRecords(txs);
        setAllBalance(openingBal);
      } catch (err) {
        if (!cancelled) {
          setAllError(formatSupabaseError(err, 'Erreur chargement journal caisse.'));
          setAllRecords([]);
          setAllBalance({ solde_initial: 0 });
        }
      } finally {
        if (!cancelled) setAllLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [isGlobalView, configured, allReloadToken]);

  useEffect(() => {
    if (viewMode !== 'day' || (!isDG && !superAdmin)) {
      setDayValidation(null);
      return;
    }
    getCashDailyValidation(selectedDate)
      .then(setDayValidation)
      .catch((err) => {
        console.warn('[CITYMO] validation caisse jour', err);
        setDayValidation(null);
      });
  }, [viewMode, isDG, superAdmin, selectedDate, records.length]);

  useEffect(() => {
    if (!isDG && !superAdmin) return;
    getPendingCashValidation(now)
      .then(setPendingJ1Validation)
      .catch(() => setPendingJ1Validation(null));
  }, [isDG, superAdmin, records.length]);

  useEffect(() => {
    if (!configured) return undefined;
    let cancelled = false;
    (async () => {
      try {
        const r = await runRhPaymentsCashBackfill();
        if (!cancelled) {
          if (r.total > 0 || r.removed > 0 || r.legacyPurged > 0) await reload();
          if (r.errors?.length) {
            notify(`${r.errors.length} erreur(s) sync RH — vérifiez RUN_FINANCE_TOUT_EN_UN.sql`);
          }
        }
      } catch (err) {
        if (!cancelled) {
          const msg = err?.message || String(err);
          if (err?.code === 'SCHEMA' || msg.includes('source_type')) {
            notify('Base Supabase incomplète — exécutez supabase/RUN_FINANCE_TOUT_EN_UN.sql puis Actualiser.');
          } else {
            console.warn('[CITYMO] backfill RH → caisse', err);
          }
        }
      }
      if (!cancelled) {
        auditRhFinanceSync().then(setRhAudit).catch(() => setRhAudit(null));
      }
    })();
    return () => { cancelled = true; };
  }, [configured]);

  function notify(msg) {
    setToast(msg);
    setTimeout(() => setToast(''), 4000);
  }

  async function handleReload() {
    setBackfilling(true);
    try {
      const r = await runRhPaymentsCashBackfill();
      await reload();
      bumpAllReload();
      const audit = await auditRhFinanceSync();
      setRhAudit(audit);
      if (r.total > 0) {
        notify(`${r.total} paiement(s) RH synchronisé(s) vers la caisse.`);
      } else if (r.legacyPurged > 0) {
        notify(`${r.legacyPurged} ancienne(s) ligne(s) hebdo supprimée(s) — affichage consolidé.`);
      } else if (r.removed > 0) {
        notify(`${r.removed} ligne(s) caisse supprimée(s) (paiements non payés).`);
      } else if ((audit.missingWorker || 0) + (audit.missingSubcontractor || 0) > 0) {
        notify(`${audit.missingWorker} ouvrier(s) et ${audit.missingSubcontractor} sous-traitant(s) payés sans ligne caisse — vérifiez les statuts « Payé ».`);
      } else if (r.errors?.length) {
        notify(`${r.errors.length} erreur(s) sync : ${r.errors[0]?.message || 'voir console'}`);
      }
    } catch (err) {
      const msg = err?.message || 'Erreur synchronisation paiements RH.';
      if (err?.code === 'SCHEMA' || err?.code === 'RLS' || msg.includes('source_type') || msg.includes('row-level security')) {
        notify('Exécutez supabase/RUN_SUPABASE_A_EXECUTER.sql dans Supabase SQL Editor, puis Actualiser.');
      } else {
        notify(msg);
      }
    } finally {
      setBackfilling(false);
    }
  }

  function isTxDayLocked(txDate) {
    if (!txDate || superAdmin) return false;
    if (viewMode !== 'day') return false;
    if (txDate !== selectedDate) return false;
    return isDayValidated;
  }

  function tryEditTx(t) {
    if (isAutoGeneratedTransaction(t)) {
      notify(getSourceModuleMessage(t));
      return;
    }
    if (isTxDayLocked(t.date)) {
      notify('Journée validée — modification impossible. Contactez le Super Admin.');
      return;
    }
    setEditTx(t);
    setShowModal(true);
  }

  async function tryRemoveTx(t) {
    if (isTxDayLocked(t.date)) {
      notify('Journée validée — suppression impossible. Contactez le Super Admin.');
      return;
    }
    const res = await removeTransaction(t.id);
    if (res?.success) bumpAllReload();
  }

  async function handleValidateDay() {
    const dateToValidate = activeDayDate;
    if (!dateToValidate) return;
    setValidating(true);
    try {
      const v = await validateCashDay(dateToValidate);
      setDayValidation(v);
      if (dateToValidate === yesterdayStr) {
        setPendingJ1Validation((p) => (p ? { ...p, validation: v, needsValidation: false } : p));
      }
      notify(`Caisse du ${formatDateFr(dateToValidate)} validée.`);
      const dayTotals = computeDailyCashTotals(cashSheetRecords, balance, dateToValidate);
      notifyCashReviewCompleted({
        reviewDate: dateToValidate,
        entrees: dayTotals.entreesJour,
        sorties: dayTotals.sortiesJour,
        soldeFin: dayTotals.soldeFinJournee,
      }).catch(() => {});
    } catch (err) {
      const msg = err?.message || 'Erreur validation.';
      if (msg.includes('row-level security') || msg.includes('daily_cash_reviews') || msg.includes('cash_daily_validations')) {
        notify('Erreur Supabase RLS — exécutez supabase/RUN_SUPABASE_A_EXECUTER.sql puis réessayez.');
      } else {
        notify(msg);
      }
    } finally {
      setValidating(false);
    }
  }

  async function handleUnlockDay() {
    if (!superAdmin) return;
    setUnlocking(true);
    try {
      await unlockCashDay(selectedDate);
      setDayValidation(null);
      notify(`Journée du ${formatDateShortFr(selectedDate)} déverrouillée.`);
    } catch (err) {
      notify(err?.message || 'Erreur déverrouillage.');
    } finally {
      setUnlocking(false);
    }
  }

  function openBalanceModal() {
    setBalForm({
      // Éditer la valeur stockée (amorce), pas le reliquat chaîné affiché.
      solde_initial: balance?.solde_initial_stored ?? balance?.solde_initial ?? '',
      alimentation: balance?.alimentation ?? 0,
      notes: balance?.notes ?? '',
      force_ouverture: Boolean(balance?.force_ouverture),
    });
    setShowBalance(true);
  }

  async function handleSaveTx(data) {
    if (isTxDayLocked(data.date)) {
      notify('Journée validée — enregistrement impossible.');
      return;
    }
    const payload = { ...data, ref: data.ref || genRef('CA') };
    const res = editTx
      ? await saveTransaction(payload, editTx.id)
      : await saveTransaction(payload);
    if (res.success) {
      setShowModal(false);
      setEditTx(null);
      bumpAllReload();
    }
  }

  async function handleSaveBalance(e) {
    e.preventDefault();
    const res = await saveBalance({
      solde_initial: parseFloat(balForm.solde_initial) || 0,
      // Conservé en base si historique, mais plus saisi à part (même nature que les entrées).
      alimentation: Number(balForm.alimentation) || Number(balance?.alimentation) || 0,
      notes: balForm.notes,
      force_ouverture: Boolean(balForm.force_ouverture),
    });
    if (res.success) {
      setShowBalance(false);
      bumpAllReload();
    }
  }

  const years = [];
  for (let y = now.getFullYear() - 2; y <= now.getFullYear() + 1; y++) years.push(y);

  function buildExportPayload() {
    if (isGlobalView) {
      return {
        year,
        month,
        periodLabel: 'Vue globale',
        filename: 'feuille-caisse-globale',
        soldeLabel: 'Solde caisse',
        transactions: allCashSheetRecords,
        totals: allTotals,
        balance: allBalance,
      };
    }
    if (isSinceResetView) {
      return {
        year,
        month,
        periodLabel: regularisationLabel
          ? `Depuis la régularisation (${regularisationLabel})`
          : 'Depuis la régularisation',
        filename: `feuille-caisse-depuis-regularisation-${year}-${String(month).padStart(2, '0')}`,
        soldeLabel: 'Solde caisse',
        transactions: sinceResetRecords,
        totals: sinceResetTotals,
        balance: { solde_initial: 0 },
      };
    }
    return { year, month, transactions: cashSheetRecords, totals, balance };
  }

  return (
    <div className="animate-fade-in">
      <div className="page-header flex-between finance-page-header">
        <div>
          <h1 className="page-title">FEUILLE DE CAISSE</h1>
          <p className="page-subtitle">
            <span className="finance-sub-hide-mobile">Journal trésorerie — paiements validés à la date réelle du paiement. </span>
            {isGlobalView
              ? <strong>Toutes périodes</strong>
              : isSinceResetView
                ? <>Depuis la régularisation <strong>{regularisationLabel}</strong></>
                : <>Mois <strong>{periodLabel}</strong></>}
            {' · '}<strong>{filterLabel}</strong>
          </p>
        </div>
        <div className="finance-page-actions">
          <button type="button" className="btn btn-secondary btn-sm" onClick={() => exportCashSheetExcel(buildExportPayload())}>
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={() => exportCashSheetPdf(buildExportPayload())}
            title={`Export PDF CITYMO v${CASH_SHEET_PDF_VERSION}`}
          >
            <Download size={14} /> PDF
          </button>
          {canManage && !isGlobalView && !isSinceResetView && (
            <button type="button" className="btn btn-secondary btn-sm" onClick={openBalanceModal}>
              <Wallet size={14} /> Solde initial
            </button>
          )}
          <button type="button" className="btn btn-secondary btn-sm" onClick={handleReload} disabled={viewLoading || backfilling}>
            <RefreshCw size={14} /> {backfilling ? 'Sync…' : 'Actualiser'}
          </button>
          {canManage && canEditDay && (
            <button type="button" className="btn btn-primary" onClick={() => { setEditTx(null); setShowModal(true); }}>
              <Plus size={15} /> Alimentation caisse
            </button>
          )}
        </div>
      </div>

      <div className="card finance-toolbar" style={{ marginBottom: 16, padding: '14px 20px' }}>
        <div className="finance-toolbar-inner">
          {!isGlobalView && (
            <>
              <select value={month} onChange={(e) => setMonth(Number(e.target.value))} style={{ ...SELECT_STYLE, maxWidth: 160 }}>
                {MOIS_OPTS.map((m) => <option key={m.v} value={m.v}>{m.l}</option>)}
              </select>
              <select value={year} onChange={(e) => setYear(Number(e.target.value))} style={{ ...SELECT_STYLE, maxWidth: 120 }}>
                {years.map((y) => <option key={y} value={y}>{y}</option>)}
              </select>
            </>
          )}
          <span className="finance-sub-hide-mobile" style={{ fontSize: '0.82rem', color: 'var(--text-3)' }}>
            {isGlobalView ? (
              <>
                Période : <strong>toutes (tous mois et années)</strong>
                {!viewLoading && displayedRecords.length > 0 ? ` — ${displayedRecords.length} op.` : ''}
              </>
            ) : isSinceResetView ? (
              <>
                Période : <strong>après le {regularisationLabel}</strong>
                {!loading ? ` — ${displayedRecords.length} op.` : ''}
              </>
            ) : (
              <>
                Période : <strong>{periodLabel}</strong>
                {isCurrentMonth ? ' (mois en cours)' : ''}
                {!loading && cashSheetRecords.length > 0 ? ` — ${cashSheetRecords.length} op. ce mois` : ''}
              </>
            )}
          </span>
          <div className="finance-toolbar-filters">
          {TABLE_FILTERS.map((f) => (
            <button
              key={f.id}
              type="button"
              className={`btn btn-sm ${tableFilter === f.id ? 'btn-primary' : 'btn-secondary'}`}
              onClick={() => selectTableFilter(f.id)}
              disabled={f.id === 'since_reset' && !regularisationDate}
              title={f.id === 'since_reset' && !regularisationDate
                ? 'Aucune régularisation caisse sur ce mois'
                : undefined}
            >
              {f.label}
            </button>
          ))}
          </div>
          {(!isCurrentMonth || isGlobalView) && (
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={() => { setYear(now.getFullYear()); setMonth(now.getMonth() + 1); setTableFilter('month'); }}
            >
              Revenir au mois en cours
            </button>
          )}
          {viewMode === 'month' && !isSinceResetView && (
            <span style={{ fontSize: '0.82rem', color: 'var(--text-3)' }}>
              {displayedRecords.length} op. sur le mois
            </span>
          )}
          {isSinceResetView && (
            <span style={{ fontSize: '0.82rem', color: 'var(--text-3)' }}>
              {displayedRecords.length} op. depuis la régularisation
            </span>
          )}
          {isGlobalView && (
            <span style={{ fontSize: '0.82rem', color: 'var(--text-3)' }}>
              {displayedRecords.length} op. au total
            </span>
          )}
        </div>
      </div>

      {!configured && (
        <div className="card" style={{ marginBottom: 16, color: 'var(--red)', padding: 14, fontSize: '0.86rem' }}>
          Supabase non configuré. Ajoutez <code>VITE_SUPABASE_URL</code> et <code>VITE_SUPABASE_ANON_KEY</code> dans votre fichier <code>.env</code>, puis redémarrez l&apos;application.
        </div>
      )}
      {viewError && <div className="card" style={{ marginBottom: 16, color: 'var(--red)', padding: 14, fontSize: '0.86rem' }}>{viewError}</div>}
      {rhAudit && !rhAudit.error && rhAudit.schemaOk && ((rhAudit.missingWorker || 0) + (rhAudit.missingSubcontractor || 0) > 0) && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF3E0', border: '1px solid #FFB74D', color: '#E65100' }}>
          <strong>Sync RH incomplète :</strong>
          {' '}{rhAudit.missingWorker} paiement(s) ouvrier(s) et {rhAudit.missingSubcontractor} sous-traitant(s) payés sans ligne caisse.
          {' '}Passez le statut à « Payé » dans Paiement hebdo, puis cliquez <strong>Actualiser</strong>.
          {rhAudit.hint && <> — {rhAudit.hint}</>}
        </div>
      )}
      {rhAudit?.error && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF3E0', border: '1px solid #FFB74D', color: '#E65100' }}>
          {rhAudit.error}
          {rhAudit.hint && <> — {rhAudit.hint}</>}
        </div>
      )}
      {toast && (
        <div className="card" style={{ marginBottom: 16, padding: '12px 16px', fontSize: '0.86rem', background: '#FFF8E1', border: '1px solid #FFE082', color: '#E65100' }}>
          {toast}
        </div>
      )}

      {isGlobalView ? (
        <div className="stat-grid finance-kpi-grid finance-kpi-strip">
          <KpiCard
            icon={<Wallet size={17} />}
            label="Reliquat"
            value={formatMAD(viewTotals.soldeInitial)}
            color="grey"
            sub={allBalance?.force_ouverture
              ? 'ouverture forcée (sans report du mois précédent)'
              : 'solde d’ouverture de la période affichée'}
          />
          <KpiCard
            icon={<Plus size={17} />}
            label="Alimentations / Entrées"
            value={formatMAD(viewTotals.totalEntrees)}
            color="green"
            sub="toutes les entrées de caisse, tous mois et années"
          />
          <KpiCard icon={<TrendingDown size={17} />} label="Sorties" value={formatMAD(viewTotals.totalSorties)} color="red" />
          <KpiCard
            icon={<Wallet size={17} />}
            label="Solde caisse"
            value={formatMAD(viewTotals.soldeMois)}
            color="blue"
            sub="reliquat + entrées − sorties"
          />
        </div>
      ) : isSinceResetView ? (
        <div className="stat-grid finance-kpi-grid finance-kpi-strip">
          <KpiCard
            icon={<Wallet size={17} />}
            label="Reliquat"
            value={formatMAD(sinceResetTotals.soldeInitial)}
            color="grey"
            sub="après régularisation (caisse soldée)"
          />
          <KpiCard
            icon={<Plus size={17} />}
            label="Alimentations / Entrées"
            value={formatMAD(sinceResetTotals.totalEntrees)}
            color="green"
            sub="entrées depuis la régularisation"
          />
          <KpiCard icon={<TrendingDown size={17} />} label="Sorties" value={formatMAD(sinceResetTotals.totalSorties)} color="red" />
          <KpiCard
            icon={<Wallet size={17} />}
            label="Solde caisse"
            value={formatMAD(sinceResetTotals.soldeMois)}
            color="blue"
            sub="reliquat + entrées − sorties"
          />
        </div>
      ) : (
        <div className="stat-grid finance-kpi-grid finance-kpi-strip">
          <KpiCard
            icon={<Wallet size={17} />}
            label="Reliquat"
            value={formatMAD(totals.soldeInitial)}
            color="grey"
            sub={balance?.force_ouverture
              ? 'ouverture forcée (sans report du mois précédent)'
              : 'reporté du mois précédent (hors alimentations)'}
          />
          <KpiCard
            icon={<Plus size={17} />}
            label="Alimentations / Entrées"
            value={formatMAD(totals.totalEntrees)}
            color="green"
            sub="toutes les entrées de caisse du mois"
          />
          <KpiCard icon={<TrendingDown size={17} />} label="Sorties" value={formatMAD(totals.totalSorties)} color="red" />
          <KpiCard
            icon={<Wallet size={17} />}
            label="Solde caisse du mois"
            value={formatMAD(totals.soldeMois)}
            color="blue"
            sub="reliquat + entrées − sorties"
          />
        </div>
      )}

      {viewLoading ? (
        <div style={{ textAlign: 'center', padding: 40 }}><Loader2 size={24} className="spin" /></div>
      ) : displayedRecords.length === 0 ? (
        <div className="card">
          <EmptyState
            icon={<Wallet size={22} />}
            title={isGlobalView
              ? 'Aucune opération — toutes périodes'
              : isSinceResetView
                ? `Aucune opération depuis le ${regularisationLabel}`
                : `Aucune opération — ${periodLabel}`}
            sub={configured && !viewError
              ? isGlobalView
                ? 'Aucune opération visible selon vos permissions.'
                : isSinceResetView
                  ? 'La caisse est soldée. La prochaine alimentation apparaîtra ici. La vue mois conserve l’historique complet.'
                  : 'Historique complet du mois. Validez un paiement dans Paiement hebdo ou Sous-traitants — la sortie s\'ajoute automatiquement à la date du paiement.'
              : 'Connectez-vous et vérifiez la configuration Supabase.'}
            action={canManage && canEditDay ? 'Alimentation manuelle' : undefined}
            onAction={canManage && canEditDay ? () => setShowModal(true) : undefined}
          />
        </div>
      ) : (
        <div className="card" style={{ padding: 0 }}>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Source</th>
                  <th>Client / Fournisseur</th>
                  <th>Description</th>
                  <th>Sortie</th>
                  <th>Entrée</th>
                  <th>Paiement</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {displayedRecords.map((t) => {
                  const isAuto = isAutoGeneratedTransaction(t) || t.isRecap;
                  const badge = getSourceBadgeLabel(t);
                  const isSelectedDay = viewMode === 'day' && t.date === selectedDate;
                  const rowLocked = isSelectedDay && isDayValidated && !superAdmin && viewMode === 'day';
                  return (
                  <tr key={t.id} style={isSelectedDay ? { background: '#E8F5E9' } : undefined}>
                    <td data-label="Date">
                      {t.date}
                      {t.date === todayStr && (
                        <span className="badge badge-green" style={{ marginLeft: 6, fontSize: '0.65rem' }}>J</span>
                      )}
                    </td>
                    <td data-label="Source">
                      <span className={`badge ${isAuto ? 'badge-blue' : 'badge-grey'}`} style={{ fontSize: '0.72rem', whiteSpace: 'nowrap' }}>
                        {badge}
                      </span>
                    </td>
                    <td data-label="Contrepartie">{t.contrepartie || '—'}</td>
                    <td data-label="Description">{t.description}</td>
                    <td data-label="Sortie" style={{ color: 'var(--red)', fontWeight: 600 }}>
                      {t.sens === 'sortie' ? formatMAD(t.montant) : '—'}
                    </td>
                    <td data-label="Entrée" style={{ color: '#2E7D32', fontWeight: 600 }}>
                      {t.sens === 'entree' ? formatMAD(t.montant) : '—'}
                    </td>
                    <td data-label="Paiement">{t.mode_paiement}</td>
                    <td data-label="Actions">
                      {!isAuto && canManage && !rowLocked && (
                        <div style={{ display: 'flex', gap: 6 }}>
                          <button type="button" className="btn btn-ghost btn-sm" onClick={() => tryEditTx(t)}><Edit2 size={13} /></button>
                          <button type="button" className="btn btn-ghost btn-sm" style={{ color: 'var(--red)' }} onClick={() => tryRemoveTx(t)}><Trash2 size={13} /></button>
                        </div>
                      )}
                      {!isAuto && canManage && rowLocked && (
                        <Lock size={14} style={{ opacity: 0.4 }} title="Journée validée" />
                      )}
                      {isAuto && (
                        <button type="button" className="btn btn-ghost btn-sm" title="Lecture seule" onClick={() => notify(getSourceModuleMessage(t))}>
                          <Edit2 size={13} style={{ opacity: 0.35 }} />
                        </button>
                      )}
                    </td>
                  </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <Modal open={showModal} onClose={() => { setShowModal(false); setEditTx(null); }} title={editTx ? 'Modifier alimentation caisse' : 'Nouvelle alimentation caisse'}>
        <TxForm
          initial={editTx || { ...EMPTY_TX, date: viewMode === 'day' ? selectedDate : todayStr }}
          onSave={handleSaveTx}
          onCancel={() => { setShowModal(false); setEditTx(null); }}
          locked={isDayValidated && !superAdmin && (editTx?.date === selectedDate || (!editTx && viewMode === 'day'))}
        />
      </Modal>

      <Modal open={showBalance} onClose={() => setShowBalance(false)} title="Paramètres du mois" width={480}>
        <form onSubmit={handleSaveBalance}>
          <p style={{ fontSize: '0.82rem', color: 'var(--text-3)', margin: '0 0 12px' }}>
            Par défaut, le <strong>reliquat</strong> est le solde final du mois précédent (automatique).
            Cochez « ouverture forcée » pour démarrer ce mois sur le montant saisi, sans report.
            Les alimentations s’enregistrent via « + Alimentation caisse ».
          </p>
          <FField label="Reliquat (amorce / correction exceptionnelle)">
            <input type="number" step="0.01" value={balForm.solde_initial} onChange={(e) => setBalForm((p) => ({ ...p, solde_initial: e.target.value }))} style={INPUT_STYLE} />
          </FField>
          <label style={{ display: 'flex', alignItems: 'flex-start', gap: 8, marginBottom: 12, fontSize: '0.85rem', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={Boolean(balForm.force_ouverture)}
              onChange={(e) => setBalForm((p) => ({ ...p, force_ouverture: e.target.checked }))}
              style={{ marginTop: 3 }}
            />
            <span>
              <strong>Ouverture forcée</strong> — ignorer le report du mois précédent
              (ex. nouveau départ juillet à 0).
            </span>
          </label>
          <FField label="Notes">
            <textarea value={balForm.notes} onChange={(e) => setBalForm((p) => ({ ...p, notes: e.target.value }))} style={{ ...INPUT_STYLE, minHeight: 64 }} />
          </FField>
          <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
            <button type="button" className="btn btn-secondary" onClick={() => setShowBalance(false)}>Annuler</button>
            <button type="submit" className="btn btn-primary" disabled={saving}>Enregistrer</button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
