import { useState, useEffect, useCallback } from 'react';
import { getSupabase, isSupabaseConfigured } from '../lib/supabase';
import { formatSupabaseError } from '../services/supabase/formatError';
import {
  listFinanceTransactions,
  createFinanceTransaction,
  updateFinanceTransaction,
  deleteFinanceTransaction,
  computeCashTotals,
  isAutoGeneratedTransaction,
  getSourceModuleMessage,
} from '../services/finance/financeTransactions';
import {
  getCashMonthlyBalance,
  upsertCashMonthlyBalance,
  resolveEffectiveBalance,
} from '../services/finance/cashMonthlyBalances';

export function useFinanceTransactions(year, month) {
  const [records, setRecords] = useState([]);
  const [balance, setBalance] = useState(null);
  const [totals, setTotals] = useState({
    soldeInitial: 0, alimentation: 0, totalEntrees: 0, totalSorties: 0, soldeMois: 0,
  });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);
  const configured = isSupabaseConfigured();

  const load = useCallback(async () => {
    if (!configured) {
      setError('Supabase non configuré — vérifiez VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY dans .env');
      setLoading(false);
      return;
    }
    if (!year || !month) {
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const [txResult, balResult] = await Promise.allSettled([
        listFinanceTransactions({ year, month }),
        getCashMonthlyBalance(year, month),
      ]);
      if (txResult.status === 'rejected') throw txResult.reason;
      const txs = txResult.value;
      const storedBal = balResult.status === 'fulfilled' ? balResult.value : null;
      if (balResult.status === 'rejected') {
        console.warn('[CITYMO] cash_monthly_balances indisponible', balResult.reason);
      }

      let effectiveBal = storedBal;
      try {
        effectiveBal = await resolveEffectiveBalance(year, month, storedBal);
      } catch (reliquatErr) {
        console.warn('[CITYMO] reliquat mensuel indisponible', reliquatErr);
        effectiveBal = {
          ...(storedBal || { annee: year, mois: month, alimentation: 0, notes: '' }),
          solde_initial: Number(storedBal?.solde_initial) || 0,
        };
      }

      setRecords(txs);
      setBalance(effectiveBal);
      setTotals(computeCashTotals(txs, effectiveBal));
    } catch (err) {
      console.error('[CITYMO] useFinanceTransactions', err);
      setError(formatSupabaseError(err, 'Erreur chargement journal caisse.'));
    } finally {
      setLoading(false);
    }
  }, [configured, year, month]);

  useEffect(() => { load(); }, [load]);

  useEffect(() => {
    if (!configured) return undefined;
    const { data: { subscription } } = getSupabase().auth.onAuthStateChange(() => { load(); });
    return () => subscription.unsubscribe();
  }, [configured, load]);

  async function saveTransaction(form, id) {
    setSaving(true);
    setError(null);
    try {
      if (id) {
        const existing = records.find((r) => r.id === id);
        if (existing && isAutoGeneratedTransaction(existing)) {
          const msg = getSourceModuleMessage(existing);
          setError(msg);
          return { success: false, error: msg };
        }
      }
      if (id) await updateFinanceTransaction(id, form);
      else await createFinanceTransaction(form);
      await load();
      return { success: true };
    } catch (err) {
      const msg = formatSupabaseError(err, 'Erreur enregistrement.');
      setError(msg);
      return { success: false, error: msg };
    } finally {
      setSaving(false);
    }
  }

  async function removeTransaction(id) {
    setSaving(true);
    try {
      const existing = records.find((r) => r.id === id);
      if (existing && isAutoGeneratedTransaction(existing)) {
        const msg = getSourceModuleMessage(existing);
        setError(msg);
        return { success: false, error: msg };
      }
      await deleteFinanceTransaction(id);
      await load();
      return { success: true };
    } catch (err) {
      const msg = formatSupabaseError(err, 'Erreur suppression.');
      setError(msg);
      return { success: false, error: msg };
    } finally {
      setSaving(false);
    }
  }

  async function saveBalance(form) {
    setSaving(true);
    try {
      await upsertCashMonthlyBalance({ ...form, annee: year, mois: month });
      // Recharge pour recalculer le reliquat (chaîne dynamique).
      await load();
      return { success: true };
    } catch (err) {
      const msg = formatSupabaseError(err, 'Erreur solde mensuel.');
      setError(msg);
      return { success: false, error: msg };
    } finally {
      setSaving(false);
    }
  }

  return {
    records, balance, totals, loading, saving, error, configured,
    reload: load, saveTransaction, removeTransaction, saveBalance,
  };
}
