/**
 * financeTransactions.js — Journal caisse (entrées / sorties)
 */
import { getSupabase } from '../../lib/supabase';
import { requireSupabaseUserId } from '../supabase/requireUser';
import {
  syncFinanceTransaction,
  FINANCE_SOURCE_TYPES,
  isAutoGeneratedTransaction,
  getSourceBadgeLabel,
  getSourceModuleMessage,
} from './financeSync';

export {
  syncFinanceTransaction,
  removeLinkedFinanceTransaction,
  removeLegacyWorkerWeeklyFinanceTransactions,
  FINANCE_SOURCE_TYPES,
  isAutoGeneratedTransaction,
  getSourceBadgeLabel,
  getSourceModuleMessage,
  resolveTransactionCategoryName,
} from './financeSync';
export { syncFacturePaymentsToCash } from './financeSync';

const TABLE = 'finance_transactions';

export const TYPES_ENTREE = [
  { value: 'alimentation_caisse', label: 'Alimentation caisse' },
  { value: 'reglement_client', label: 'Règlement client' },
  { value: 'remboursement', label: 'Remboursement' },
  { value: 'autre_entree', label: 'Autre entrée' },
];

export const TYPES_SORTIE = [
  { value: 'charge', label: 'Charge / dépense' },
  { value: 'ordre_paiement', label: 'Ordre de paiement' },
  { value: 'autre_sortie', label: 'Autre sortie' },
];

export function normalizeTransaction(row) {
  if (!row) return null;
  return {
    id: row.id,
    date: row.date_operation || '',
    sens: row.sens || 'sortie',
    type_operation: row.type_operation || 'autre',
    contrepartie: row.contrepartie || '',
    description: row.description || '',
    montant: Number(row.montant) || 0,
    mode_paiement: row.mode_paiement || 'Espèces',
    category_id: row.category_id || null,
    project_id: row.project_id || null,
    vehicle_id: row.vehicle_id || null,
    worker_id: row.worker_id || null,
    client_id: row.client_id || null,
    invoice_id: row.invoice_id || null,
    charge_id: row.charge_id || null,
    payment_order_id: row.payment_order_id || null,
    source_type: row.source_type || null,
    source_id: row.source_id || null,
    source_module: row.source_module || null,
    is_auto_generated: row.is_auto_generated ?? false,
    validation_status: row.validation_status || 'pending',
    synced_at: row.synced_at || null,
    ref: row.ref_operation || '',
    statut: row.statut || 'Validé',
    created_at: row.created_at,
  };
}

export function toTransactionRow(form) {
  const sens = form.sens || (form.montant_entree ? 'entree' : 'sortie');
  return {
    date_operation: form.date || null,
    sens,
    type_operation: form.type_operation || (sens === 'entree' ? 'autre_entree' : 'autre_sortie'),
    contrepartie: form.contrepartie || null,
    description: (form.description || '').trim(),
    montant: Number(form.montant ?? form.montant_entree ?? form.montant_sortie) || 0,
    mode_paiement: form.mode_paiement || 'Espèces',
    category_id: form.category_id || null,
    project_id: form.project_id || null,
    vehicle_id: form.vehicle_id || null,
    worker_id: form.worker_id || null,
    client_id: form.client_id || null,
    invoice_id: form.invoice_id || null,
    charge_id: form.charge_id || null,
    payment_order_id: form.payment_order_id || null,
    ref_operation: form.ref || null,
    statut: form.statut || 'Validé',
  };
}

export async function listFinanceTransactions({ year, month } = {}) {
  let q = getSupabase().from(TABLE).select('*').order('date_operation', { ascending: true });
  if (year && month) {
    const start = `${year}-${String(month).padStart(2, '0')}-01`;
    const endMonth = month === 12 ? 1 : month + 1;
    const endYear = month === 12 ? year + 1 : year;
    const end = `${endYear}-${String(endMonth).padStart(2, '0')}-01`;
    q = q.gte('date_operation', start).lt('date_operation', end);
  } else if (year && !month) {
    const start = `${year}-01-01`;
    const end = `${year + 1}-01-01`;
    q = q.gte('date_operation', start).lt('date_operation', end);
  }
  const { data, error } = await q;
  if (error) throw error;
  return (data || []).map(normalizeTransaction);
}

export async function listFinanceTransactionsForYear(year) {
  return listFinanceTransactions({ year });
}

export async function createFinanceTransaction(form) {
  const uid = await requireSupabaseUserId();
  const row = {
    ...toTransactionRow(form),
    is_auto_generated: false,
    validation_status: 'pending',
  };
  if (form.type_operation === 'alimentation_caisse') {
    row.source_type = FINANCE_SOURCE_TYPES.CASH_FUNDING;
    row.source_module = 'finance';
  }
  const { data, error } = await getSupabase()
    .from(TABLE)
    .insert([{ ...row, created_by: uid }])
    .select()
    .single();
  if (error) throw error;
  return normalizeTransaction(data);
}

async function assertManualTransaction(id) {
  const { data, error } = await getSupabase()
    .from(TABLE)
    .select('id, is_auto_generated, source_type, charge_id, payment_order_id')
    .eq('id', id)
    .maybeSingle();
  if (error) throw error;
  if (!data) {
    const err = new Error('Opération introuvable.');
    err.code = 'NOT_FOUND';
    throw err;
  }
  if (isAutoGeneratedTransaction(normalizeTransaction(data))) {
    const err = new Error(getSourceModuleMessage(normalizeTransaction(data)));
    err.code = 'AUTO_LOCKED';
    throw err;
  }
}

export async function updateFinanceTransaction(id, form) {
  await requireSupabaseUserId();
  await assertManualTransaction(id);
  const { data, error } = await getSupabase()
    .from(TABLE)
    .update(toTransactionRow(form))
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return normalizeTransaction(data);
}

export async function deleteFinanceTransaction(id) {
  await requireSupabaseUserId();
  await assertManualTransaction(id);
  const { error } = await getSupabase().from(TABLE).delete().eq('id', id);
  if (error) throw error;
}

export function computeCashTotals(transactions, balanceRow) {
  const soldeInitial = Number(balanceRow?.solde_initial) || 0;
  const alimentation = Number(balanceRow?.alimentation) || 0;
  let totalEntrees = 0;
  let totalSorties = 0;
  (transactions || []).forEach((t) => {
    if (t.statut === 'Annulé') return;
    if (t.sens === 'entree') totalEntrees += t.montant || 0;
    else totalSorties += t.montant || 0;
  });
  const soldeMois = soldeInitial + alimentation + totalEntrees - totalSorties;
  return { soldeInitial, alimentation, totalEntrees, totalSorties, soldeMois };
}

export async function syncChargeToTransaction(charge) {
  if (!charge?.id) return;
  return syncFinanceTransaction(FINANCE_SOURCE_TYPES.CHARGE, charge.id, { entity: charge });
}

export async function syncPaymentOrderToTransaction(order) {
  if (!order?.id) return;
  return syncFinanceTransaction(FINANCE_SOURCE_TYPES.PAYMENT_ORDER, order.id, { entity: order });
}

/** Rattrapage RH → feuille de caisse (ouvriers + sous-traitants déjà payés). */
export async function runRhPaymentsCashBackfill() {
  const { backfillWorkerPayrollToCash } = await import('../rh/workerPayroll');
  const { backfillSubcontractorPaymentsToCash } = await import('../rh/subcontractors');
  const [payrollRes, subcontractorRes] = await Promise.all([
    backfillWorkerPayrollToCash(),
    backfillSubcontractorPaymentsToCash(),
  ]);
  const payroll = payrollRes?.synced ?? 0;
  const subcontractor = subcontractorRes?.synced ?? 0;
  const legacyPurged = payrollRes?.legacyPurged ?? 0;
  const removed = (payrollRes?.removed ?? 0) + (subcontractorRes?.removed ?? 0);
  const errors = [...(payrollRes?.errors || []), ...(subcontractorRes?.errors || [])];
  return { payroll, subcontractor, removed, legacyPurged, total: payroll + subcontractor, errors };
}
